if(typeof VIPSHOP=="undefined")var VIPSHOP={};VIPSHOP.core2=true;
(function($){VIPSHOP.config={pmsHost:"http://pms.vip.com"};Function.prototype.method=function(name,fn){if(typeof this.prototype[name]=="undefined")this.prototype[name]=fn;return this};String.method("encode",function(noCom){return noCom?encodeURI(this):encodeURIComponent(this)}).method("decode",function(noCom){return noCom?decodeURI(this):decodeURIComponent(this)});VIPSHOP.isMobile="createTouch"in document||/(iPhone|iPad|iPod|Android)/i.test(navigator.userAgent);VIPSHOP.isIE6=navigator.appVersion.indexOf("MSIE 6")>
-1;var webpCache={};VIPSHOP.webp=function(feature,callback){var kTestImages={lossy:"UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEADsD+JaQAA3AAAAAA",lossless:"UklGRhoAAABXRUJQVlA4TA0AAAAvAAAAEAcQERGIiP4HAA==",alpha:"UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAARBxAR/Q9ERP8DAABWUDggGAAAABQBAJ0BKgEAAQAAAP4AAA3AAP7mtQAAAA==",animation:"UklGRlIAAABXRUJQVlA4WAoAAAASAAAAAAAAAAAAQU5JTQYAAAD/////AABBTk1GJgAAAAAAAAAAAAAAAAAAAGQAAABWUDhMDQAAAC8AAAAQBxAREYiI/gcA"};var img=new Image;var fCache=webpCache[feature];
if(typeof fCache=="boolean")if(fCache)callback(feature,true);else callback(feature,false);else{img.onload=function(){var result=img.width>0&&img.height>0;webpCache[feature]=result;callback(feature,result)};img.onerror=function(){webpCache[feature]=false;callback(feature,false)};img.src="data:image/webp;base64,"+kTestImages[feature]}};VIPSHOP.errorReport=function(msg,fileUrl,fileLine){var _ua=navigator.userAgent,target,mouseX,mouseY,docST=$(document).scrollTop(),docSL=$(document).scrollLeft(),errorContent;
$(function(){$(document).mousemove(function(e){target=e.target;mouseX=e.pageX;mouseY=e.pageY});setTimeout(function(){errorContent={_ua:_ua,url:location.href,fileUrl:fileUrl,fileLine:fileLine,msg:msg,docST:docST,docSL:docSL,target:target,mouseX:mouseX,mouseY:mouseY}},10)})};window.onerror=VIPSHOP.errorReport;VIPSHOP.guid=function(pre){return(pre||"VIPSHOP_")+ +new Date+(Math.random()+"").slice(-8)};VIPSHOP.zIndexManager=function(){if(!VIPSHOP.maxIndex){var zIndexArr=$.map($("body > *"),function(i,
n){var obj=$(i),zIndexVal;if(obj.css("position")!="static"){zIndexVal=obj.css("zIndex");return zIndexVal=="auto"?0:zIndexVal-0}});if(zIndexArr.length==0)zIndexArr.push(1);var MaxZ=Math.max.apply(null,zIndexArr);if(MaxZ>=214748E4){VIPSHOP.maxIndex=214748E4;VIPSHOP.log("zIndex\u5df2\u7ecf\u8d85\u8fc7\u6700\u5927\u503c")}else VIPSHOP.maxIndex=MaxZ}return++VIPSHOP.maxIndex};VIPSHOP.namespace=function(str){var arr=str.split("."),o=VIPSHOP;for(var i=arr[0]=="VIPSHOP"?1:0;i<arr.length;i++){o[arr[i]]=o[arr[i]]||
{};o=o[arr[i]]}return o};VIPSHOP.parentCls=function(){};VIPSHOP.parentCls.prototype={get:function(args){var prop=this[args];return $.isFunction(prop)?prop.apply(this,Array.prototype.slice.call(args,1)):prop}};VIPSHOP.log=function(msg){if(window["console"])try{console["log"].apply(console,arguments)}catch(e){console["log"](msg)}return this};VIPSHOP.JSS=function(jQueryObj){var targetDom=jQueryObj?jQueryObj:$(".J_widget"),widget;targetDom.each(function(){var value,_eval,nsCrackArr,s,$data={},dataRes=
$(this).data();for(var i in dataRes){value=dataRes[i];if(typeof value=="string"){nsCrackArr=value.split(".");if(/^(?:\$.*|\{.*\}|\[.*\]|null|false|true|NaN)$/.test(value)||(+value+""===value||window[nsCrackArr[0]]))_eval=true;else _eval=false;try{if(!window[nsCrackArr[0]])data=_eval?eval("0,"+value):value;else{s=window;for(var j=0,len=nsCrackArr.length;j<len;j++)s=s[nsCrackArr[j]];data=s}}catch(e){data=value}$data[i]=data}}if(widget=$(this)[$data.widget])widget.call($(this),$data)});return this};
$(function(){VIPSHOP.JSS()});VIPSHOP.queryStringToJSON=function(url){if(url==="")return"";var pairs=(url||location.search).replace(/^\?/,"").split("&");var result={};for(var i=0,len=pairs.length;i<len;i++){var pair=pairs[i].split("=");if(!!pair[0])result[pair[0]]=decodeURIComponent(pair[1]||"")}return result};VIPSHOP.setSead=function(settings){for(var cur=0,len=settings.length;cur<len;cur++){var target=$(settings[cur].target),attr=settings[cur].attr,data=settings[cur].data;target.each(function(i,
n){for(var k in attr){var attrVal=attr[k];if($.type(attr[k])==="function")attrVal=attr[k].call($(n),i)||"";$(n).attr(k,attrVal)}for(var j in data){var dataVal=data[j];if($.type(data[j])==="function")dataVal=data[j].call($(n),i)||"";$(n).data(j,dataVal)}})}$.Listeners.pub("setSeadDone").success();return this};(function(){var _crackName=function(name){var index=name.lastIndexOf("."),clsName,o,args;if(index!=-1){args=name.substring(0,index);o=VIPSHOP.namespace(args);clsName=name.substring(index+1,name.length)}else{clsName=
name;o=VIPSHOP}return{clsName:clsName,o:o}};$.extend(VIPSHOP,{extend:function(subCls,superCls){if(!$.isFunction(subCls)||!$.isFunction(superCls))return false;var F=function(){},subClsProp;F.prototype=superCls.prototype;subClsProp=subCls.prototype=new F;subCls.prototype.constructor=subCls;subCls.superclass=superCls.prototype;return subCls},declare:function(subCls,superCls,prop){var o=_crackName(subCls);var subCls=o.o[o.clsName]=function(opts){if(superCls){if($.isFunction(superCls)&&superCls.prototype._init)superCls._init=
superCls.prototype._init;superCls._init&&superCls._init.call(this,opts)}prop._init.call(this,opts);if(opts&&opts.plugins)for(var i=0;i<opts.plugins.length;i++)this.usePlugin(opts.plugins[i])};if(superCls)VIPSHOP.extend(subCls,superCls);for(var key in prop){subCls.prototype[key]=prop[key];if(typeof prop[key]=="function"&&key!="_init")subCls.prototype[key].supername=key}subCls.prototype._meta={};subCls.prototype._meta.className=o.clsName;if(superCls){subCls.prototype.supermethod=function(args){if(args.callee.supername)return subCls.superclass[args.callee.supername]()};
subCls.prototype.getSuperMethod=function(name){if(subCls.superclass[name])return subCls.superclass[name]}}subCls.prototype._plugins={};subCls.prototype.addPlugin=function(name,callback){this._plugins[name]=callback;if(callback.methods)$.extend(subCls.prototype,callback.methods)};subCls.prototype.usePlugin=function(name){if(this._plugins[name]&&typeof this._plugins[name]==="function")this._plugins[name]();else if(this._plugins[name]._init)this._plugins[name]._init.call(this);else VIPSHOP.log("\u8fd8\u6ca1\u6709\u4e3a "+
o.clsName+" \u5b9a\u4e49 "+name+" \u63d2\u4ef6")};subCls.prototype.useObject=function(name,opts){var config;if(typeof obj=="function")try{var node=this.node;if(this.node instanceof jQuery)node=this.node[0];if(opts)config=$.extend({},opts,{node:node});else config={node:node};new obj(config)}catch(e){VIPSHOP.log(e,"\u8c8c\u4f3c\u6ca1\u6709\u4e3a\u5176\u4f5c\u4e3a\u63d2\u4ef6\u63a5\u53e3")}else VIPSHOP.log(obj,"\u4e0d\u5b58\u5728\u8fd9\u4e2a\u6784\u9020\u51fd\u6570\uff01")}},plugin:function(name,obj,
callback){obj.prototype.addPlugin(name,callback)}})})();VIPSHOP.bridgeTojQuery=function(methodName,widget){var methodArray=$.trim(methodName).split(",");jQuery.each(methodArray,function(i,n){jQuery.fn[n]=function(config,args){var args=Array.prototype.slice.call(arguments,1),Obj,R,_widget,method,getWidgetData;var hasWidget=jQuery(this).data("widget_"+n);if(typeof config!="string"&&hasWidget){hasWidget.destroy&&hasWidget.destroy();jQuery(this).removeData("widget_"+n)}if(config=="destroy"){getWidgetData=
jQuery(this).data("widget_"+n);if(getWidgetData){getWidgetData.destroy&&getWidgetData.destroy();$(this).removeData("widget_"+n);return}else return true}else if(typeof config=="string"){if(config.indexOf("_")==0){VIPSHOP.log("\u4e0d\u80fd\u8c03\u7528\u79c1\u6709\u65b9\u6cd5");return false}_widget=$(this).data("widget_"+n);method=_widget?_widget[config]:null;if(method){R=method.apply(_widget,args);if(R===_widget||typeof R=="undefined")return this;else return R}}else{config=$.extend({},config,{node:this});
Obj=new widget(config);Obj[n]=function(func){var args=Array.prototype.slice.call(arguments,1);var R=Obj[func](args);return R};$(this).data("widget_"+n,Obj);return this}};$[n]=function(options){return new widget(options)}})};if(!jQuery.browser){var uaMatch=function(ua){var ua=ua.toLowerCase();var match=/(chrome)[ \/]([\w.]+)/.exec(ua)||(/(webkit)[ \/]([\w.]+)/.exec(ua)||(/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(ua)||(/(msie) ([\w.]+)/.exec(ua)||(ua.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(ua)||
[]))));return{browser:match[1]||"",version:match[2]||"0"}},matched=uaMatch(navigator.userAgent),browser={};if(matched.browser){browser[matched.browser]=true;browser.version=matched.version}if(browser.chrome)browser.webkit=true;else if(browser.webkit)browser.safari=true;jQuery.browser=browser}})(jQuery);
jQuery.Loader={_queue:[],_modules:[],_loaded:[],pagelet:function(pars){if(typeof pars.css!="undefined"&&pars.css.length)this.style(pars.css);if(typeof pars.pid!="undefined"&&pars.pid!="")pars.pid=$(pars.pid);else pars.pid=$("body");var loadQueue=[];if(typeof pars.json!="undefined")if($.isArray(pars.json))for(var i=0,j=pars.json.length;i<j;i++)loadQueue.push('$.getJSON("'+pars.json[i]+'", function (d) { $.extend(pars.pid.data(), d); })');else if(typeof pars.json=="object")loadQueue.push("$.extend(pars.pid.data(), pars.json);");
if(typeof pars.html!="undefined"&&pars.html!="")loadQueue.push('pars.pid.load("'+pars.html+'")');var q=eval("$.when("+loadQueue.join(",")+")");q.done(function(){if(typeof pars.js=="function")pars.js();else $.Loader.script(pars.js)});return this},style:function(herf){if(typeof herf==="string"){var styleTag=document.createElement("link");styleTag.setAttribute("rel","stylesheet");styleTag.setAttribute("href",herf);$("head")[0].appendChild(styleTag)}else if(herf.length>0)for(var i=0,j=herf.length;i<j;i++)this.style(herf[i]);
return this},script:function(src){if(typeof src==="string")$.ajax({url:src,dataType:"script",cache:true});else if(src.length>0)for(var i=0,j=src.length;i<j;i++)this.script(src[i]);return this},advScript:function(){for(var i=0,j=arguments.length;i<j;i++){var module=$.extend({},arguments[i],{req:0});if(this._loaded[module.name])continue;this._modules[module.name]=module;if($.isArray(module.requires)&&module.requires.length>0)module.req=module.requires.length;this._queue.push(module)}this._Execute();
return this},_Execute:function(){if(this._queue.length<=0)return;var index=0;while(src=this._queue[index]){if(this._loaded[src.name]){this._queue.splice(index,1);continue}if($.isArray(src.requires)&&src.requires.length>0)for(var i=0,j=src.requires.length;i<j;i++)if(this._loaded[src.requires[i]]){src.req--;src.requires.splice(i,1);i--}if(src.req>0){index++;continue}if(src.url){this._queue.splice(index,1);$.ajax({url:src.url,dataType:"script",context:{name:src.name},cache:true,success:function(){$.Loader._loaded[this.name]=
1;$.Loader._Execute()}})}else{src.def&&src.def();this._loaded[src.name]=1;this._queue.splice(index,1)}}}};
(function(){var escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,meta={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};function quote(string){return'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"'}function f(n){return n<10?"0"+n:n}function str(key,holder){var i,v,len,partial,value=holder[key],
type=typeof value;if(value&&(typeof value==="object"&&typeof value.toJSON==="function")){value=value.toJSON(key);type=typeof value}switch(type){case "string":return quote(value);case "number":return isFinite(value)?String(value):"null";case "boolean":return String(value);case "object":if(!value)return"null";switch(Object.prototype.toString.call(value)){case "[object Date]":return isFinite(value.valueOf())?'"'+value.getUTCFullYear()+"-"+f(value.getUTCMonth()+1)+"-"+f(value.getUTCDate())+"T"+f(value.getUTCHours())+
":"+f(value.getUTCMinutes())+":"+f(value.getUTCSeconds())+"Z"+'"':"null";case "[object Array]":len=value.length;partial=[];for(i=0;i<len;i++)partial.push(str(i,value)||"null");return"["+partial.join(",")+"]";default:partial=[];for(i in value)if(Object.prototype.hasOwnProperty.call(value,i)){v=str(i,value);if(v)partial.push(quote(i)+":"+v)}return"{"+partial.join(",")+"}"}}}function stringifyJSON(value){return str("",{"":value})}jQuery.stringifyJSON=stringifyJSON})();
jQuery.Cookie={set:function(name,value,domain,path,hour){if(hour){var today=new Date;var expire=new Date;expire.setTime(today.getTime()+36E5*hour)}document.cookie=name+"="+escape(value)+"; "+(hour?"expires="+expire.toGMTString()+"; ":"")+(path?"path="+path+"; ":"path=/; ")+(domain?"domain="+domain+";":".vip.com;");return true},get:function(name){var r=new RegExp("(?:^|;+|\\s+)"+name+"=([^;]*)");var m=document.cookie.match(r);return unescape(decodeURIComponent(!m?"":m[1]))},del:function(name,domain,
path){document.cookie=name+"=; expires=Mon, 26 Jul 1997 05:00:00 GMT; "+(path?"path="+path+"; ":"path=/; ")+(domain?"domain="+domain+";":".vip.com;")}};
jQuery.Storage=function(){var rule1=!jQuery.browser.msie;var rule2=jQuery.browser.msie&&jQuery.browser.version-0>=8;if(rule1||rule2){try{localStorage.setItem("localStorageTest",1)}catch(e){return{set:$.noop,get:function(){return""},remove:$.noop}}localStorage.removeItem("localStorageTest")}if(window.localStorage)return function(){var method={set:function(key,value,expires){var v=[];if(expires){var d=(new Date).getTime();v.push({"expires":d+expires*1E3})}v.push(value);localStorage.setItem(key,$.stringifyJSON(v))},
get:function(key){var value=localStorage.getItem(key);if(value==null||value==undefined){value="";return value}try{value=$.parseJSON(value)}catch(e){}if(typeof value!="object")return value;if($.type(value[0])=="string")return value[0];if($.type(value)=="object")return value;var expires=value[0].expires;if(expires&&/^\d{13,}$/.test(expires)){var d=(new Date).getTime();if(expires<=d){localStorage.removeItem(key);return""}value.shift()}return value[0]},remove:function(key){localStorage.removeItem(key)}};
var d=(new Date).getTime();for(key in localStorage){var v=localStorage.getItem(key);try{v=$.parseJSON(v)}catch(e){}if(Object.prototype.toString.call(v).toLowerCase().indexOf("array")>0){var expires=v[0].expires;if(expires&&(/^\d{13,}$/.test(expires)&&expires<=d))localStorage.removeItem(key)}}return method}();else return function(){var storage=null;var hostName="vip.com";function buildInput(){try{if(!storage){storage=document.createElement("INPUT");storage.type="hidden";storage.style.display="none";
storage.addBehavior("#default#userData");document.body.appendChild(storage);var expires=new Date;expires.setDate(expires.getDate()+365);storage.expires=expires.toUTCString()}}catch(e){VIPSHOP.log(e);return}}return{set:function(key,value,expires){buildInput();var v=[];if(expires){var d=(new Date).getTime();v.push({"expires":d+expires*1E3})}v.push(value);storage.load(hostName);storage.setAttribute(key,$.stringifyJSON(v));storage.save(hostName)},get:function(key){buildInput();storage.load(hostName);
var value=storage.getAttribute(key);if(value==null||value==undefined){value="";return value}try{value=$.parseJSON(value)}catch(e){}if($.type(value[0])=="string")return value[0];if($.type(value)=="object")return value;if(typeof value!="object")return value;var expires=value[0].expires;if(expires&&/^\d{13,}$/.test(expires)){var d=(new Date).getTime();if(expires<=d){storage.load(hostName);storage.removeAttribute(key);storage.save(hostName);return""}value.shift()}return value[0]},remove:function(key){buildInput();
storage.load(hostName);storage.removeAttribute(key);storage.save(hostName)}}}()}();
$(function(){jQuery.crossStorage={status:"unload",iframe:"http://s2.vipstatic.com/html/public/helper/crossStorage.html",messenger:"http://s2.vipstatic.com/js/public/plugins/messenger.js",data:null,hasSub:false,cbList:{},cbs:{set:{},get:{}},id:0,loadRes:function(cbObj){var self=this;if(this.status=="unload"){this.status="loading";var ifrObj=document.createElement("iframe");ifrObj.src=this.iframe;ifrObj.setAttribute("width",0);ifrObj.setAttribute("height",0);ifrObj.setAttribute("style","display: none");
if(ifrObj.attachEvent)ifrObj.attachEvent("onload",function(){self._loadMessenger(ifrObj)});else ifrObj.onload=function(){self._loadMessenger(ifrObj)};$("body")[0].appendChild(ifrObj)}if(this.status!="loaded"){var cbType=cbObj.type;this.cbList[cbType]=cbObj.func;if(!self.hasSub){self.hasSub=true;$.Listeners.sub("csHelper").onsuccess(function(data){var ifrWindow=data.ifrObj.contentWindow;data.messenger=new Messenger("parent","CS");data.messenger.addTarget(ifrWindow,"csHelper");data.messenger.listen(self.listeners);
self.status="loaded";self.data=data;for(var i in self.cbList)self.cbList[i](data)})}}else cbObj.func(this.data)},_loadMessenger:function(ifrObj){var self=this;$.ajax({url:self.messenger,type:"GET",dataType:"script",cache:true,success:function(){$.Listeners.pub("csHelper").success({ifrObj:ifrObj})}})},createId:function(){return++this.id},listeners:function(msg){var self=$.crossStorage;var msgObj=$.parseJSON(msg);var method=msgObj.method;var key=msgObj.key;var val=msgObj.val;var cbFunc=self.cbs[method][key];
var id=msgObj.id;cbFunc[id].cb&&cbFunc[id].cb(val);delete cbFunc[id]},set:function(key,val,expires,cb){var self=this;if(!cb){cb=expires;expires=undefined}var id=this.createId();var setObj={method:"set",id:id,key:key,val:val,expires:expires,cb:cb};var setCbs=self.cbs.set;if(!setCbs[key])setCbs[key]={};setCbs[key][id]=setObj;this.loadRes({type:"set",func:function(data){var messenger=data.messenger;for(var cbKey in setCbs)for(var id in setCbs[cbKey]){var o=setCbs[cbKey][id];if(!o.hasSend){o.hasSend=
true;var s=$.stringifyJSON(o);messenger.targets.csHelper.send(s)}}}})},get:function(key,cb){var self=this;var id=this.createId();var getObj={method:"get",id:id,key:key,cb:cb};var getCbs=self.cbs.get;if(!getCbs[key])getCbs[key]={};getCbs[key][id]=getObj;this.loadRes({type:"get",func:function(data){var messenger=data.messenger;for(var cbKey in getCbs)for(var id in getCbs[cbKey]){var o=getCbs[cbKey][id];if(!o.hasSend){o.hasSend=true;var s=$.stringifyJSON(o);messenger.targets.csHelper.send(s)}}}})}}});
function Subject(subName,subNameSpace,data){this.subName=subName;this.subNameSpace=subNameSpace;this.allowSuccessFlag=true;this.allowErrorFlag=true;this.hasSuccess=subNameSpace[subName]["hasSuccess"]||false;this.hasError=subNameSpace[subName]["hasError"]||false;this.callbacks={"onsuccess":new Callbacks,"onerrors":new Callbacks};this.data=data||{}}
Subject.prototype={onsuccess:function(callbackFunc){this._when("onsuccess",callbackFunc);return this},onerror:function(callbackFunc){this._when("onerrors",callbackFunc);return this},ononce:function(callbackFunc){this._when("ononce",callbackFunc);return this},trigger:function(type,data){var callbacks=this.callbacks,that=this;switch(type){case "onsuccess":status="hasSuccess";break;case "onerrors":status="hasError";break;default:break}that[status]=true;if(that[status]&&this.allowSuccessFlag)callbacks[type].fire(data)},
unsub:function(type){switch(type){case "success":this.allowSuccessFlag=false;break;case "error":this.allowErrorFlag=false;break;default:this.allowSuccessFlag=false;this.allowErrorFlag=false}},_when:function(type,callbackFunc){var callbacks=this.callbacks,status,allow,that=this;switch(type){case "onsuccess":callbacks["onsuccess"].add(callbackFunc);status="hasSuccess";allow="allowSuccessFlag";break;case "onerrors":callbacks["onerrors"].add(callbackFunc);status="hasError";allow="allowErrorFlag";break;
case "ononce":var i=0;var subNameList=that.subNameSpace[that.subName].subNameList;var len=callbacks["onsuccess"].list.length;var funcStr=callbackFunc.toString();var lsFuncStr="";var isSame=false;for(var k in subNameList){var lsFunc=subNameList[k].callbacks.onsuccess.list[0];var lsFuncStr=lsFunc?lsFunc.toString():"";if(funcStr==lsFuncStr)isSame=true}if(!isSame)that._when("onsuccess",callbackFunc);else{status="hasSuccess";allow="allowSuccessFlag";type="onsuccess"}break;default:break}var deps=that.subName.split(",");
var doneCount=0;var extData={};for(var i=0,len=deps.length;i<len;i++)if(that.subNameSpace[deps[i]]&&that.subNameSpace[deps[i]][status]==true){extData=$.extend(extData,that.subNameSpace[deps[i]]["data"][type]);doneCount++}if(doneCount==len&&that[allow])callbackFunc(extData)}};function Callbacks(){this.list=[]}
Callbacks.prototype={add:function(func){var list=this.list;var type=$.isFunction(func);for(var i=0,len=list.length+1;i<len;i++)if(type&&func!=list[i])list.push(func)},fire:function(){var list=this.list;var args=arguments;for(var i=0,len=list.length;i<len;i++)list[i].apply(null,args)}};
$.Listeners={version:"1.0.1.20130109",subNameSpace:{},hasPubList:[],subNameList:[],sub:function(subName){if(typeof subName!="string")return;var subNameSpace=this.subNameSpace,_t=Math.floor(Math.random()*(new Date).getTime()+1),args=Array.prototype.slice.call(arguments),subjectObj;subName=args.join(",");if(!subNameSpace[subName])subNameSpace[subName]={subNameList:{}};subjectObj=new Subject(subName,subNameSpace,subNameSpace[subName].data);subjectObj["_t"]=_t;subNameSpace[subName]["subNameList"]["subjectObj_"+
_t]=subjectObj;return subjectObj},_facade:function(subName,type,data){var subNameSpace=this.subNameSpace,hasState;switch(type){case "onsuccess":hasState="hasSuccess";break;case "onerrors":hasState="hasError";break;default:break}!subNameSpace[subName]["data"]&&(subNameSpace[subName]["data"]={});subNameSpace[subName]["data"][type]=$.extend({},subNameSpace[subName]["data"][type],data);subNameSpace[subName][hasState]=true;if($.inArray(subName,this.hasPubList)==-1)this.hasPubList.push(subName);for(var i in subNameSpace){var arr=
i.split(",");var len=count=arr.length;var extData={};if($.inArray(subName,arr)!=-1){for(var j=0;j<len;j++)if($.inArray(arr[j],this.hasPubList)!=-1){extData=$.extend(extData,subNameSpace[arr[j]]["data"][type]);count--}if(count==0)for(var k in subNameSpace[i]["subNameList"])subNameSpace[i]["subNameList"][k].trigger(type,extData)}}},pub:function(subName){var subNameSpace=this.subNameSpace,callbackType,args=Array.prototype.slice.call(arguments),that=this;for(var i=0,len=args.length;i<len;i++){subName=
args[i];if(!subNameSpace[subName])subNameSpace[subName]={subNameList:{}}}return{success:function(data){for(var i=0,len=args.length;i<len;i++)that._facade(args[i],"onsuccess",data);return this},error:function(data){for(var i=0,len=args.length;i<len;i++)that._facade(args[i],"onerrors",data);return this}}},reset:function(subName){var hasPubList=this.hasPubList;var subNameSpace=this.subNameSpace;var index=$.inArray(subName,hasPubList);if(index!=-1){hasPubList.splice(index,1);delete subNameSpace[subName];
for(var i in subNameSpace){var tempArr=i.split(",");if($.inArray(subName,tempArr)!=-1)delete subNameSpace[i]["data"]}}return this},unsub:function(subName){var subNameSpace=this.subNameSpace;var facade;if(subNameSpace[subName]){facade=function(type,key){if(key){var _t=key._t;var subjectObj=subNameSpace[subName]["subNameList"]["subjectObj_"+_t];subjectObj.unsub(type)}else for(var i in subNameSpace[subName]["subNameList"])subNameSpace[subName]["subNameList"][i].unsub(type)};return{success:function(key){facade("success",
key);return this},error:function(key){facade("error",key);return this},all:function(){facade();return this}}}else{var rtnNoop=function(){return this};return{success:rtnNoop,error:rtnNoop,all:rtnNoop}}},show:function(subName){var _cacheObj={}.cacheObj;var subNameSpace=this.subNameSpace;function CreateCacheObj(subName){var i,conditionStart="",conditionEnd="";if(subName){i=subName;if(!subNameSpace[subName]){VIPSHOP.log("can not find the subject!");return}}else{conditionStart="for (var i in subNameSpace) {";
conditionEnd="}"}var property="_cacheObj[i] = {};"+'_cacheObj[i]["onsuccess"] = [];'+'_cacheObj[i]["onerrors"] = [];'+'for (var j in subNameSpace[i]["subNameList"]) {'+'_cacheObj[i]["onsuccess"] = _cacheObj[i]["onsuccess"].concat(subNameSpace[i]["subNameList"][j]["callbacks"]["onsuccess"]["list"]);'+'_cacheObj[i]["onerrors"] = _cacheObj[i]["onerrors"].concat(subNameSpace[i]["subNameList"][j]["callbacks"]["onerrors"]["list"]);'+"}";returns="return _cacheObj";var func=new Function("subNameSpace","_cacheObj",
"i",conditionStart+property+conditionEnd+returns);_cacheObj=func(subNameSpace,{},i);return _cacheObj}cacheObj=CreateCacheObj(subName);return{success:function(){if(subName)VIPSHOP.log(cacheObj[subName]["onsuccess"]);else VIPSHOP.log(cacheObj)},error:function(){if(subName)VIPSHOP.log(cacheObj[subName]["onerrors"]);else VIPSHOP.log(cacheObj)},all:function(){VIPSHOP.log(cacheObj)}}}};
(function($){VIPSHOP.member={info:null,chk:function(){var loginID=$.Cookie.get("VipLID"),account=$.Cookie.get("login_username");if(loginID){var afterTxt=$("#J_header_logAfter").html();var userName=$.Cookie.get("VipRNAME");$("#J_head_log").addClass("login_after").removeClass("login_before").html(afterTxt.replace("{$J_header_account}",fn_cutString(userName,9)));$("#J_header_lnkLogOut").on("click",function(){location.href=VIPSHOP.userHost+"/logout?src="+encodeURIComponent(window.location.href)});this.info=
{"account":account,"level":parseInt($.Cookie.get("VipMonopoly")),"nickname":userName};$.Listeners.pub("loginSuccess").success();return}$("#J_head_log").addClass("login_before").removeClass("login_after").html($("#J_header_logBefor").html());$("#J_header_lnkLogin").on("click",function(){location.href=VIPSHOP.userHost+"/login?src="+encodeURIComponent(window.location.href)});$("#J_header_lnkRegister").on("click",function(){location.href=VIPSHOP.userHost+"/register?src="+encodeURIComponent(window.location.href)});
$.Listeners.pub("unLogin").success();return},viewed:function(cookie_name,merchandise_id){var viewed=$.Cookie.get(cookie_name);if(viewed=="")var arViewed=[];else var arViewed=viewed.split(",");var viewed=-1;for(var i=0;i<arViewed.length;i++)if(arViewed[i]==merchandise_id)viewed=i;if(viewed==-1&&arViewed.length>=5)arViewed.shift();else if(viewed>-1)arViewed.splice(viewed,1);arViewed.push(merchandise_id);var domain=document.domain.split(".");domain.shift();var rootDomain=domain.join(".");$.Cookie.set(cookie_name,
arViewed.join(","),rootDomain)},setViewed:function(channel,merchandise){var data=$.Storage.get(channel),arrMer=!!data?data:[],newMer=[];if(arrMer){var arrLength=arguments.length>2?arguments[2]:5,forLength=arrLength;if(arrMer.length<arrLength)forLength=arrMer.length;for(var i=0;i<forLength;i++)if(arrMer[i].id!=merchandise.id)newMer.push(arrMer[i]);if(newMer.length>=arrLength)newMer.shift()}newMer.push(merchandise);$.Storage.set(channel,newMer)},getViewed:function(channel){var data=$.Storage.get(channel);
return!!data?data:[]}}})(jQuery);
(function($){VIPSHOP.interactDialog=function(options){var frameUrls={login:"https://passport.vip.com/login?gotype=2",setPwd:"https://myi.vip.com/wallet/to_set_pay_pwd_component"};this.msgPlugin=VIPSHOP.staticJs+"/plugins/messenger.js";this.frameUrl=frameUrls[options.type];this.dialogIsFixed=false;this.zIndex=900;$.extend(this,options);this._init()};$.extend(VIPSHOP.interactDialog.prototype,{setDialogHeight:function(height){var that=this;var dialogW={login:430,setPwd:550};that.dialog.size(dialogW[this.type],
height).getElem(".login_iframe").attr("height",height)},closeDialog:function(data){this.closeEvent.call(this,data);this.dialog.close()},loginSuccess:function(){var that=this;that.closeDialog.call(that);that.loginEvent.call(that)},setPwdSuccess:function(){this.setPwdEvent.call(this)},loginEvent:$.noop,setPwdEvent:$.noop,closeEvent:$.noop,_init:function(){var that=this;$.ajax({url:that.msgPlugin,dataType:"script",cache:true,success:function(){that.openDialog()}})},openDialog:function(){var that=this;
var size={};if(this.type=="login"){size.w=430;size.h=610}if(this.type=="setPwd"){size.w=500;size.h=600}var iframeHtml="<div>"+'<iframe class="login_iframe" frameborder="0" scrolling="no" width="'+size.w+'" height="'+size.h+'" src="'+that.frameUrl+'">'+"</div>";var dialog=$.Dialog({model:true,elStyle:"login_dialog",opacity:0.3,size:[430,610],content:iframeHtml,isFixed:that.dialogIsFixed,zIndex:that.zIndex,showEvent:function(){if(that.type=="login"){var messenger=new Messenger("loginDialog","vip.com");
messenger.listen(function(msg){VIPSHOP.log(msg);var queryObj=VIPSHOP.queryStringToJSON(msg);var method=queryObj["method"];var args=queryObj.args;that[method].call(that,args)})}if(that.type=="setPwd"){var messenger=new Messenger("parent","vip.com");messenger.listen(function(msg){VIPSHOP.log(msg);var msgObj=eval("("+msg+")");var queryObj=VIPSHOP.queryStringToJSON(msgObj.message);if(msgObj.code==10243)that.setDialogHeight(queryObj.compHeight);if(msgObj.code==10241||(msgObj.code==10242||msgObj.code==
10244))that.closeDialog(msgObj);if(msgObj.code==200||msgObj.code==1052){that.st&&clearTimeout(that.st);that.st=setTimeout(function(){that.closeDialog(msgObj);that.setPwdSuccess(msgObj)},1500)}})}}}).open();that.dialog=dialog}});VIPSHOP.login={};VIPSHOP.login.init=function(options){options=$.extend({type:"login"},options);return new VIPSHOP.interactDialog(options)};VIPSHOP.setPwd={};VIPSHOP.setPwd.init=function(options){options=$.extend({type:"setPwd"},options);return new VIPSHOP.interactDialog(options)}})(jQuery);
(function($){VIPSHOP.declare("Form",null,{defaults:{trigger:"",timeout:6E3,errorF:function(){},submitBefor:function(){return true},callbackAfter:function(){}},_init:function(option){var that=this,options;options=that.options=$.extend({},this.defaults,option);if(typeof options.trigger=="string"&&options.trigger.length)options.trigger=$(options.trigger);if(options.trigger)this._set(options);return that},_set:function(parms){parms.trigger.on("submit",function(){var objF=$(this);if(parms.submitBefor.call(objF)){objF.find("button[type=submit]").prop("disabled",
true);$.ajax({url:objF.attr("action"),data:objF.serialize(),timeout:parms.timeout,dataType:"jsonp",error:function(){if(objF.find("button[type=submit]").length)objF.find("button[type=submit]").html(objF.find("button[type=submit]").val()).prop("disabled",false);parms.errorF()},success:function(re){if(objF.find("button[type=submit]").length)objF.find("button[type=submit]").html(objF.find("button[type=submit]").val()).prop("disabled",false);parms.callbackAfter.call(objF,re);objF[0].reset()}})}return false})}});
VIPSHOP.bridgeTojQuery("form,Form",VIPSHOP.Form)})(jQuery);var __originals={st:setTimeout,si:setInterval};eval("var setTimeout, setInterval;");setTimeout=__originals.st;setInterval=__originals.si;__originals=undefined;var __si=setInterval;window.setInterval=function(callback,timeout,param){var _cb=function(){callback.call(null,param)};return __si(_cb,timeout)};var __st=setTimeout;window.setTimeout=function(callback,timeout,param){var _cb=function(){callback.call(null,param)};return __st(_cb,timeout)};
(function($){VIPSHOP.declare("Switchable",null,{defaults:{_triggers:[],_panels:[],_prev:null,_next:null,nowOn:0,count:0,multiple:false,effect:"",activeCls:"active",autoPlay:false,interval:1E3,overPause:false,activeIndex:0,delay:500,pervCls:null,nextCls:null,trigger:"click",triggerCls:"",switchEvent:null,firstCls:"switchable-first",lastCls:"switchable-last"},_init:function(option){var that=this,options,node;options=that.options=$.extend({},that.defaults,option);node=that.node=$(options.node);options.owner=
node;options._panels=node.find(options.panelCls);options.count=options._panels.length;this.bindTriggerEvent();node.data({setting:options});if(options.effect=="slideX")this.setWrapWidth();options.prevBtn=node.find(options.pervCls);options.nextBtn=node.find(options.nextCls);if(options.pervCls)options.prevBtn.on("click",function(){that.prev(options)});if(options.nextCls)options.nextBtn.on("click",function(){that.next(options)});if(options.autoPlay){that.start();if(options.overPause)node.on({"mouseenter":function(){that.stop()},
"mouseleave":function(){that.start()}})}if(options.activeIndex>=0)that.switchTo.call(null,options,options.activeIndex);return this},setWrapWidth:function(){var options=this.options;var _panels=options._panels=options.node.find(options.panelCls);var panelOuterWidth=options._panels.outerWidth();var panelMargin=parseInt(options._panels.css("marginLeft"))+parseInt(options._panels.css("marginRight"));var count=options.count=options.node.find(options.panelCls).length;var width=(panelOuterWidth+panelMargin)*
count;options.scroller&&$(options.scroller,options.node).width(width);return this},bindTriggerEvent:function(){var that=this,options=this.options,node=$(options.node);if(options.triggerCls){options._triggers=node.find(options.triggerCls);options._triggers.each(function(n){$(this).data({index:n})});if(options.trigger=="click"){options._triggers.off("click.switchable");options._triggers.on("click.switchable",options,function(){that.switchTo($(this))})}if(options.trigger=="over"){var hoverTimer;options._triggers.off("mouseenter.switchable").off("mouseleave.switchable");
options._triggers.on("mouseenter.switchable",options,function(e){clearTimeout(hoverTimer);hoverTimer=window.setTimeout(function(e){that.switchTo($(e.currentTarget))},e.data.delay,e)}).on("mouseleave.switchable",function(){clearTimeout(hoverTimer)})}}return this},switchTo:function(){var setting,index,flag,prevBtn,nextBtn;if(arguments.length==1){setting=this.options;if(typeof arguments[0]=="number"){index=arguments[0];if(index<0)index=0;if(index>setting.count)index=setting.count-1}else index=arguments[0].data("index")}else{setting=
arguments[0];index=arguments[1]}if(!setting.multiple)if(setting.effect!="slideX"&&setting.effect!="slideY")$(setting._panels,this.node).hide();prevBtn=setting.owner.find(setting.pervCls);nextBtn=setting.owner.find(setting.nextCls);if(setting.effect!="")switch(setting.effect){case "slideX":if(flag!==false)$(setting.scroller,setting.owner).stop(true,true).animate({"marginLeft":-setting.slideXWidth*index});else return false;break;case "slideY":$(setting.scroller,setting.owner).stop(true,true).animate({"marginTop":-setting.slideYHeight*
index});break;default:eval("$(setting._panels[index])."+setting.effect+"Toggle();")}else $(setting._panels[index]).toggle();var lazyload=$(setting._panels[index]).find(".datalazyload");if(lazyload.length>0)$(setting._panels[index]).html(lazyload.val());$(setting._triggers).removeClass(setting.activeCls);$(setting._triggers[index]).toggleClass(setting.activeCls);setting.nowOn=index;if(index+setting.visiNum>=setting.count){setting.nextBtn.addClass(setting.lastCls);setting.prevBtn.removeClass(setting.firstCls)}else if(index==
0){setting.prevBtn.addClass(setting.firstCls);setting.nextBtn.removeClass(setting.lastCls)}else{setting.prevBtn.removeClass(setting.firstCls);setting.nextBtn.removeClass(setting.lastCls)}setting.switchEvent&&setting.switchEvent($(setting._triggers[index]),$(setting._panels[index]));return this},prev:function(){var that=this,options=that.options,n,slideNum=options.slideNum||1,flag=true;if(options.nowOn-slideNum<0){n=options.count-slideNum;flag=options.firstEvent&&options.firstEvent.call(options.node)}else n=
options.nowOn-slideNum;if(flag!==false)return that.switchTo.call(null,options,n)},next:function(){var that=this,options=that.options,n,flag=true,slideNum=options.slideNum||1,j=options.visiNum?options.visiNum-slideNum:0;if(options.nowOn+slideNum>=options.count-j){n=0;flag=options.lastEvent&&options.lastEvent.call(options.node)}else n=options.nowOn+slideNum;if(flag!==false)return that.switchTo.call(null,options,n)},start:function(){var that=this,v_data=$(that.options.node).data();clearInterval(v_data.timing);
v_data.timing=window.setInterval(function(){that.next()},v_data.setting.interval,{data:v_data.setting});return this},stop:function(){clearInterval($(this.node).data("timing"));return this}});VIPSHOP.bridgeTojQuery("switchable,Switchable",VIPSHOP.Switchable)})(jQuery);
(function($){VIPSHOP.declare("Switchable2",null,{defaults:{_triggers:[],_panels:[],_prev:null,_next:null,nowOn:0,count:0,visiNum:1,multiple:false,effect:"",activeCls:"active",autoPlay:false,interval:1E3,overPause:false,activeIndex:0,delay:500,pervCls:null,nextCls:null,trigger:"click",switchEvent:$.noop,panelCls:".bd",triggerCls:""},_init:function(option){var that=this,options,node;options=that.options=$.extend({},that.defaults,option,true);node=that.node=$(options.node);options.pannelDom=$(options.panelCls);
options.triggerDom=$(options.triggerCls);options.prevDom=$(options.pervCls);options.nextDom=$(options.nextCls);options.childs=options.pannelDom.children();options.firstChild=options.childs.eq(0);$(window).on("resize.switchable orientationchange.switchable",function(){var childML=options.firstChild.css("marginLeft");var childMR=options.firstChild.css("marginRight");var childMT=options.firstChild.css("marginTop");var childMB=options.firstChild.css("marginBottom");options.childWidth=options.firstChild.outerWidth(true)+
parseInt(childML!="auto"?childML:0)+parseInt(childMR!="auto"?childMR:0);options.childHeight=options.firstChild.outerHeight(true)+parseInt(childMT!="auto"?childMT:0)+parseInt(childMB!="auto"?childMB:0);options.childLen=options.childs.length;that._destory();that.setStyle();that.setWrapWidth();that.bindTriggerEvent();that.bindSwipeEvent();that.autoPlay()}).trigger("resize.switchable");return this},autoPlay:function(){var options=this.options;if(options.autoPlay){var proxyEvt=$.proxy(this.next,this);
options._interval&&clearInterval(options._interval);options._interval=setInterval(proxyEvt,options.interval);this.node.off("mouseenter.switchable mouseleave.switchable").on({"mouseenter.switchable":function(){clearInterval(options._interval)},"mouseleave.switchable":function(){clearInterval(options._interval);options._interval=setInterval(proxyEvt,options.interval)}})}},setStyle:function(){var that=this;var options=that.options;switch(options.effect){case "slideXLoop":case "slideX":var pannelDomParent=
options.pannelDom.parent();if(pannelDomParent.css("position")!="relative")pannelDomParent.css("position","relative");if(options.pannelDom.css("position")!="absolute")options.pannelDom.css("position","absolute");options.pannelDom.children().css("float","left");break;default:break}},setWrapWidth:function(){var that=this;var options=that.options;switch(options.effect){case "slideXLoop":case "slideYLoop":options.childs.slice(0,options.visiNum).clone().addClass("loop_clone_next").appendTo(options.pannelDom);
options.childs.slice(options.childLen-options.visiNum).clone().addClass("loop_clone_prev").prependTo(options.pannelDom);if(options.effect=="slideXLoop")options.pannelDom.css({position:"absolute",width:options.childWidth*(options.childLen+options.visiNum*2),height:options.childHeight,left:-options.childWidth*options.visiNum,top:0});else if(options.effect=="slideYLoop")options.pannelDom.css({position:"absolute",width:options.childWidth,height:options.childHeight*(options.childLen+options.visiNum*2),
top:-options.childHeight*options.visiNum,left:0});break;case "slideX":options.pannelDom.css({width:options.childWidth*options.childLen,left:0});default:break}return this},bindTriggerEvent:function(){var that=this;var options=that.options;switch(options.effect){case "slideXLoop":case "slideYLoop":case "slideX":options.triggerDom.children().on("click.switchable",function(){var index=$(this).index();$(this).addClass(options.activeCls).siblings().removeClass(options.activeCls);that.switchTo(index)}).eq(options.activeIndex).trigger("click.switchable");
that.lazyload(options.firstChild);break;default:break}options.nextDom.on("click.switchable",$.proxy(that.next,that));options.prevDom.on("click.switchable",$.proxy(that.prev,that));return this},bindSwipeEvent:function(){var that=this;var wrapNode=this.node;var options=this.options;if(VIPSHOP.isMobile){var wrapNodeOffset={};var pannelDomPos={};var startPos={};var movePos={};var diff={};options.pannelDom.on("touchstart.switchable",function(e){if(!that.scrolling){var touches=e.originalEvent.changedTouches[0];
wrapNodeOffset.x=wrapNode.offset().left;wrapNodeOffset.y=wrapNode.offset().top;startPos.x=touches.pageX-wrapNodeOffset.x;startPos.y=touches.pageY-wrapNodeOffset.y;pannelDomPos.left=parseInt($(this).css("left"))||0;pannelDomPos.top=parseInt($(this).css("top"))||0}else{wrapNodeOffset={};pannelDomPos={};startPos={}}options._interval&&clearInterval(options._interval)}).on("touchmove.switchable",function(e){if(!that.scrolling){var firstPage,lastPage;var touches=e.originalEvent.changedTouches[0];movePos.x=
touches.pageX-wrapNodeOffset.x;movePos.y=touches.pageY-wrapNodeOffset.y;diff.x=movePos.x-startPos.x;diff.y=movePos.y-startPos.y;var transTo;if(options.effect==="slideXLoop"||options.effect==="slideX"){if(Math.abs(diff.x)>10&&Math.abs(diff.y)<=20){transTo={left:pannelDomPos.left+diff.x};e.originalEvent.preventDefault()}else if(diff.x.toString()=="NaN")e.originalEvent.preventDefault();if(Math.abs(diff.x)<Math.abs(diff.y))diff.x=0}else if(options.effect==="slideYLoop"||options.effect==="slideY")if(Math.abs(diff.y)>
10){e.originalEvent.preventDefault();transTo={top:pannelDomPos.top+diff.y}}else if(diff.y.toString()=="NaN")e.originalEvent.preventDefault();if(options.effect==="slideX"||options.effect==="slideY"){if(options.nowOn==0&&diff.x>0)transTo=null;if(options.nowOn==Math.ceil(options.childLen/options.visiNum)-1&&diff.x<0)transTo=null}transTo&&$(this).css(transTo)}else e.originalEvent.preventDefault()}).on("touchend.switchable",function(e){var hasSlide;var direction;if(!that.scrolling){if(options.effect===
"slideXLoop"||options.effect=="slideX"){hasSlide=Math.abs(diff.x);direction=diff.x<0?"left":"right"}else if(options.effect==="slideYLoop"||options.effect=="slideY"){hasSlide=Math.abs(diff.y);direction=diff.y<0?"up":"down"}if(hasSlide>100)if(direction=="left"||direction=="up")that.next();else{if(direction=="right"||direction=="down")that.prev()}else that.switchTo(options.nowOn)}that.autoPlay()})}},switchTo:function(i){if(this.scrolling)return;var that=this;var options=that.options;var target=i%options.childLen;
var pageNums=Math.round(options.childLen/options.visiNum);if(i===pageNums)target=0;switch(options.effect){case "slideXLoop":case "slideYLoop":var transitTo;var orienTo;if(i>options.nowOn){if(options.effect=="slideXLoop"){transitTo={"left":-(i+1)*options.childWidth*options.visiNum};orienTo={"left":-(target+1)*options.childWidth*options.visiNum}}else{transitTo={"top":-(i+1)*options.childHeight*options.visiNum};orienTo={"top":-(target+1)*options.childHeight*options.visiNum}}that.scrolling=true;options.pannelDom.animate(transitTo,
300,function(){$(this).css(orienTo);that.triggerAddCls(Math.abs(target));options.nowOn=target;that.scrolling=false})}else if(i<options.nowOn){var orient=i==-1?pageNums:i+1;if(options.effect=="slideXLoop"){transitTo={"left":-(i+1)*options.childWidth*options.visiNum};orienTo={"left":-orient*options.childWidth*options.visiNum}}else{transitTo={"top":-(i+1)*options.childHeight*options.visiNum};orienTo={"top":-orient*options.childHeight*options.visiNum}}that.scrolling=true;options.pannelDom.animate(transitTo,
300,function(){$(this).css(orienTo);that.triggerAddCls(i);options.nowOn=i==-1?pageNums-1:i;that.scrolling=false})}else{that.scrolling=true;if(options.effect=="slideXLoop")options.pannelDom.stop(true,false).animate({"left":-(i+1)*options.childWidth*options.visiNum},300,function(){that.scrolling=false});else if(options.effect=="slideYLoop")options.pannelDom.stop(true,false).animate({"top":-(i+1)*options.childHeight*options.visiNum},300,function(){that.scrolling=false})}break;case "slideX":var proxyEvt=
$.proxy(that.next,that);options._interval&&clearInterval(options._interval);if(i<0)return;if(i==Math.ceil(options.childLen/options.visiNum))return;that.scrolling=true;options.pannelDom.stop(true,false).animate({"left":-target*options.childWidth*options.visiNum},300,function(){that.scrolling=false;that.triggerAddCls(target);options.nowOn=i});if(options.autoPlay&&options.interval)options._interval=setInterval(proxyEvt,options.interval);break;default:break}var curPannel=options.pannelDom.children().eq(i+
1);that.lazyload(curPannel);var I=i%options.childLen;if(I<0)I=options.childLen-1;options.switchEvent(I);return this},ctrlTrigger:function(i,orientation){var options=this.options;var childLen=options.childs.length;var triggerVisiNum=options.triggerVisiNum;var firstTrigger=options.triggerDom.children().first();var firstTriggerH=firstTrigger.outerHeight(true);options.overView=options.overView||0;options.firstTriOnView=options.firstTriOnView||0;options.lastTriOnView=options.lastTriOnView||triggerVisiNum-
1;if(childLen===triggerVisiNum)return;if(orientation==="next")if(i>options.lastTriOnView){options.firstTriOnView+=1;options.lastTriOnView+=1;options.overView+=1}else if(i===0){options.firstTriOnView=0;options.lastTriOnView=triggerVisiNum-1;options.overView=0}if(orientation==="prev")if(i<=options.firstTriOnView){options.firstTriOnView-=1;options.lastTriOnView-=1;options.overView-=1}else if(i==childLen-1){options.firstTriOnView=childLen-triggerVisiNum-1;options.lastTriOnView=childLen-1;options.overView=
childLen-triggerVisiNum}if(options.overView<0)options.overView=0;options.triggerDom.stop(true,false).animate({top:-firstTriggerH*options.overView},"normal")},lazyload:function(target){$(target).find("img.lazy").each(function(i,n){var jqN=$(n);jqN.attr("src",jqN.data("original"));jqN.removeClass("lazy")});return this},prev:function(){var that=this;var options=that.options;var i=options.nowOn;i--;switch(options.effect){case "slideXLoop":case "slideX":that.switchTo(i);break;default:options.nowOn=i;break}return this},
next:function(){var that=this;var options=that.options;var childLen=options.pannelDom.children().length;var i=options.nowOn;i++;switch(options.effect){case "slideXLoop":case "slideX":that.switchTo(i);break;default:options.nowOn=i;break}return this},start:function(){var that=this;var options=that.options;return this},stop:function(){return this},triggerAddCls:function(i){var that=this;var options=that.options;options.triggerDom.children().eq(i).addClass(options.activeCls).siblings().removeClass(options.activeCls)},
_destory:function(){var options=this.options;options.pannelDom.off("touchstart.switchable").off("touchmove.switchable").off("touchend.switchable").find(".loop_clone_prev, .loop_clone_next").remove();options.nextDom.off("click.switchable");options.prevDom.off("click.switchable");options.triggerDom.children().off("click.switchable");this.node.off("mouseenter.switchable");this.node.off("mouseleave.switchable")},destory:function(){$(window).off("resize.switchable orientationchange.switchable");this._destory()}});
VIPSHOP.bridgeTojQuery("switchable2,Switchable2",VIPSHOP.Switchable2)})(jQuery);
(function($){var zIndex=1E3;function zIndexManager(){return++zIndex}VIPSHOP.declare("Dialog",VIPSHOP.parentCls,{id:null,defaults:{size:[500,300],position:[],content:null,title:null,effect:{effect:"slide",duration:500},model:false,elStyle:"",button:[],trigger:null,triggerType:"",showEvent:null,zIndex:null,opacity:0.1,maskColor:"black",isFixed:true,mars_pop:"",isCache:false,autoResize:false},selects:[],buffObj:null,isOpenFlag:false,dialogColletion:{count:0,maskZIndex:[]},dialogTemplates:'<div style="display:none;">'+
'<div class="_diaTitle"></div>'+'<div class="_diaContent"></div>'+'<div class="_diaButton"></div>'+"</div>",_init:function(option){var that=this,contentStyle={},posType,options,dialogTemplates,buffObj;this.id=VIPSHOP.guid();this.selects=[];this.buffObj=null;this.tag=0;options=that.options=$.extend({},this.defaults,option);that.dialogTemplates=dialogTemplates=$(that.dialogTemplates);buffObj=that.buffObj={dialog:dialogTemplates,diaTitle:dialogTemplates.find("> div:eq(0)"),diaContent:dialogTemplates.find("> div:eq(1)"),
diaButton:dialogTemplates.find("> div:eq(2)")};if(options.isFixed)posType="fixed";else posType="absolute";dialogTemplates.css({"position":posType});that.title(options.title).size(options.size[0],options.size[1]).button();if(options.elStyle)buffObj.dialog.removeClass().addClass(options.elStyle);if(options.node)options.trigger=options.node||options.trigger;if(options.trigger)$(options.trigger).on(options.triggerType+".dialog",function(){that.open()});return this},_createMask:function(){var that=this;
var options=that.options;var jqBackground=$("#_diaBackground");var selects=that.selects=$("select:not(#_diaWrap select):visible");var maskZIndex=options.zIndex?options.zIndex:zIndexManager();options.model&&this.dialogColletion.maskZIndex.push(maskZIndex);if(jqBackground.length==0){var maskDiv=that.maskDiv=$("<div id='_diaBackground'></div>");var sizeCss="width:100%; "+"height:100%;"+"background:"+options.maskColor+";"+"opacity:"+options.opacity+";"+"filter:alpha(opacity="+Number(options.opacity)*
100+")"+";"+"z-index:"+maskZIndex+";"+"display:none";var ie6Css=VIPSHOP.isIE6?"position:absolute; width:100%; height:"+$(document).height()+"px;":"";maskDiv[0].style.cssText=sizeCss+";position:fixed;top:0; left:0; overflow:hidden;"+ie6Css;$("body").append(maskDiv);maskDiv.show()}else that.maskDiv=jqBackground.css({display:"block",zIndex:maskZIndex});VIPSHOP.isIE6&&selects.css({visibility:"hidden"});return this},removeMask:function(){var that=this;that.maskDiv.animate({opacity:0},300,function(){$(this).remove()});
VIPSHOP.isIE6&&selects.css({visibility:"hidden"});return this},title:function(text){var titleWrap=this.buffObj.diaTitle;var text=text||this.options.title;if(!text)titleWrap.remove();else titleWrap.html(text).show();return this},content:function(msg){var options=this.options;var contentWrap=this.buffObj.diaContent;if(typeof msg=="undefined")return this;else{if($.type(msg)==="object")msg=$(msg).html();contentWrap.html(msg).show();if(options.autoResize){var cnt=contentWrap.children().eq(0);var w=cnt.outerWidth(true);
var h=cnt.outerHeight(true);this.size(w,h).position()}}return this},button:function(arr){var that=this,options=that.options,buffObj=that.buffObj;if($.isArray(arr))options.button=arr;if(options.button&&($.isArray(options.button)&&options.button.length>0)){buffObj.diaButton.show();for(var i=0,len=options.button.length;i<len;i++){var btn=options.button[i];var btnType=btn[0].length==0?"button":btn[0];var btnVal=btn[1].length==0?"\u6309\u94ae":btn[1];var btnListener=that.btnListener=that.btnListener||
{};var btnTag=$('<button type="'+btnType+'" id="_btnDialog_'+i+'" value="'+btnVal+'">'+btnVal+"</button>");btnListener[btnVal]=btn[2];btnTag.on("click",function(){btnListener[this.value]&&btnListener[this.value].call(that)});buffObj.diaButton.append(btnTag)}}else buffObj.diaButton.remove();return this},size:function(width,height){var that=this,options=that.options;var w=width||options.size[0];var h=height||options.size[1];this.buffObj.dialog.width(w).height(h);return this},getMid:function(){var scrollLeft=
$(document).scrollLeft(),dW=$(document).width(),buffObj=this.buffObj,mid=(dW-buffObj.dialog.outerWidth(true))/2-scrollLeft+"px";return mid},getVertical:function(){var scrollTop=$(document).scrollTop(),cH=$(window).height(),buffObj=this.buffObj,vertical=(cH-buffObj.dialog.outerHeight(true))/2+"px";return vertical},position:function(left,top){var that=this,options=that.options,contentStyle={},pos,buffObj=that.buffObj;if(options.position.length)switch(options.position.length){case 3:pos=$(options.position[0]).position();
contentStyle={top:pos.top+options.position[1],left:pos.left+options.position[2]};break;case 2:contentStyle["left"]=options.position[1];contentStyle["top"]=options.position[0];case 1:contentStyle["top"]=options.position[0];contentStyle["left"]=that.getMid();break}else{contentStyle["left"]=that.getMid();contentStyle["top"]=that.getVertical()}if(!options.isFixed)contentStyle["top"]=$(window).scrollTop()+parseInt(contentStyle["top"]);that.contentStyle=contentStyle;buffObj.dialog.css({left:contentStyle["left"],
top:contentStyle["top"]});if(VIPSHOP.isIE6){buffObj.dialog.css({position:"absolute"});if(options.isFixed)$(window).scroll(function(){buffObj.dialog[0].style.top=Number((contentStyle["top"]+"").replace(/px/,""))+$(document).scrollTop()+"px"}).trigger("scroll")}return this},open:function(){var that=this,options=that.options,dialogTop,buffObj=that.buffObj;if(!that.isOpenFlag){that.dialogColletion.count++;that.isOpenFlag=true}else return this;if($("body").find(that.buffObj.dialog).length==0){$("body").append(that.dialogTemplates);
that.content(options.content)}else options.isCache?buffObj.dialog.show():that.content(options.content);options.model&&that._createMask();that.buffObj.dialog[0].style.zIndex=options.zIndex?options.zIndex+1:zIndexManager();that.position();switch(options.effect.effect){case "fade":buffObj.dialog.stop().fadeIn(options.effect.duration);break;case "slide":dialogTop=buffObj.dialog.css("top").replace(/px/,"");buffObj.dialog.css({opacity:0,display:"block",top:dialogTop-0+10+"px"});setTimeout(function(){buffObj.dialog.stop().animate({top:dialogTop,
opacity:1},options.effect.duration)},0);break;default:buffObj.dialog.stop().show(options.effect.duration)}if(options.mars_pop!="")$.Listeners.pub("mars.pop").success({"mars_pop":options.mars_pop});$(window).off("resize."+that.id).on("resize."+that.id,function(){that.resize()});that.resize();options.showEvent&&options.showEvent.call(options.node);return this},resize:function(left,top){this.position(left,top);return this},remove:function(){this.buffObj.dialog.html("").remove()},destroy:function(){var that=
this,options=that.options;$(options.trigger).off(options.triggerType+".dialog");that.remove()},close:function(){var that=this,options=that.options,buffObj=that.buffObj,contentStyle=that.contentStyle,dialogTop;if(typeof selects!="undefined")selects.show();if(that.isOpenFlag===true&&that.dialogColletion.count>0){that.dialogColletion.count--;that.isOpenFlag=false;var mzList=that.dialogColletion.maskZIndex;var lastMZ;mzList.pop();lastMZ=mzList[mzList.length-1];if(lastMZ)$("#_diaBackground").css("zIndex",
lastMZ)}switch(options.effect.effect){case "fade":buffObj.dialog.stop().animate({"opacity":0},options.effect.duration,function(){$(this).css({"display":"none","opacity":1})});break;case "slide":dialogTop=buffObj.dialog.css("top").replace(/px/,"");buffObj.dialog.stop().animate({top:dialogTop-10,opacity:0},options.effect.duration,function(){$(this).css({top:dialogTop-0+"px",display:"none"})});break;default:buffObj.dialog.stop().hide(options.effect.duration)}if(that.maskDiv&&that.dialogColletion.count<=
0)that.maskDiv.hide();$(window).off("resize."+that.id);return this},getElem:function(str){return this.dialogTemplates.find(str)}});VIPSHOP.bridgeTojQuery("dialog,Dialog",VIPSHOP.Dialog)})(jQuery);
(function($){VIPSHOP.declare("Selector",null,{defaults:{everyLoad:false,multiple:false,target:null,targetType:"click",classPre:"",loaded:false,defTxt:"",evtChoose:null,autoWidth:false},_init:function(option){var that=this,defaults=that.defaults,hoverFlag=false,hoverTime,selectorWrapId,selectorWrap,selectorTxt,selectorOpt,options;if(!option.target)option.target=$(option.node);options=that.options=$.extend({},this.defaults,option);if(typeof options.clone=="string"){selectorWrapId=that.selectorWrapId=
options.clone.replace("#","");options.clone=$(options.clone);if($(options.clone).length==0){selectorWrap=options.clone=that.selectorWrap=$('<div id="'+selectorWrapId+'" class="'+options.classPre+'_root"></div>');selectorTxt=that.selectorTxt=$('<div class="'+options.classPre+'_txt">'+options.defTxt+"</div>");selectorOpt=that.selectorOpt=$('<div class="'+options.classPre+'_sel"></div>');selectorWrap.append(selectorTxt).append(selectorOpt);options.target.after(selectorWrap)}else{selectorWrap=that.selectorWrap=
options.clone;selectorTxt=that.selectorTxt=selectorWrap.find("."+options.classPre+"_txt");selectorOpt=that.selectorOpt=selectorWrap.find("."+options.classPre+"_sel")}}options.target.hide();if(VIPSHOP.isIE6)setTimeout(function(){options.target.css({"visibility":"hidden"})},0);if(options.autoWidth)that.autoWidth();selectorOpt.hide();that._bindSelectorTxt();return this},autoWidth:function(){var options=this.options;this.render();this.selectorOpt.show();this.selectorOpt.css({"visibility":"hidden","position":"absolute",
"minHeight":"999px"});var opts=this.selectorOpt.find("."+options.classPre+"_opt");opts.css({"width":"auto"});var widthArr=[];opts.each(function(i,n){widthArr.push($(n).width())});var maxWidth=Math.max.apply(null,widthArr)+4;var txtPaddingR=parseInt(this.selectorTxt.css("paddingRight"));var paddingR=20;paddingR=txtPaddingR-4>paddingR?txtPaddingR:paddingR;paddingR=$.browser.msie?13:paddingR;this.selectorTxt.css("width",maxWidth);opts.css({"width":maxWidth+8,"paddingRight":paddingR-8});this.selectorOpt.css({"visibility":"",
"position":"","minHeight":""})},reset:function(){var that=this,options=that.options;that.selectorWrap.find("."+options.classPre+"_optCur").removeClass(options.classPre+"_optCur");that.selectorTxt.html(options.defTxt);options.target.val("");return this},debug:function(){VIPSHOP.log(this.options);return this},click:function(){var that=this,options=that.options;if(arguments.length==1)options.clone.find("."+options.classPre+"_opt:eq("+arguments[0]+")").trigger("click");else options.clone.find("."+options.classPre+
"_opt[data-val="+arguments[1]+"]").trigger("click");return this},render:function(){this._render();return this},show:function(){this._show();this._bindEvent();return this},hide:function(){this._hide();this._unbindEvent();return this},disable:function(){var that=this,options=this.options;that.selectorTxt.addClass("selector_disable");that._unbindSelectorTxt();return this},enable:function(){var that=this,options=this.options;that.selectorTxt.removeClass("selector_disable");that._bindSelectorTxt();return this},
_bindSelectorTxt:function(){var that=this,options=that.options;switch(options.targetType){case "click":that.selectorTxt.on("click",function(e){that.show()});break;case "mouse":that.selectorTxt.on({"mouseenter":function(){that.show();hoverFlag=true},"mouseleave":function(){that.hoverTime=hoverTime=setTimeout(function(){that.hide();hoverFlag=false},200)}});break}return this},_unbindSelectorTxt:function(){var that=this,options=that.options;switch(options.targetType){case "click":that.selectorTxt.off("click");
break;case "mouse":that.selectorTxt.off("hover");break}return this},_show:function(){var that=this,options=that.options;that.selectorWrap.append(that.selectorOpt);if((options.everyLoad||!options.loaded)&&!that.selectorOpt.is(":visible"))that._render(options);else if(that.selectorOpt.is(":visible"))that._hide();that.selectorWrap.find("."+options.classPre+"_sel").show();that.isShowed=true;return false},_bindEvent:function(){var that=this,options=that.options;switch(options.targetType){case "click":$(document).on("click.selector_"+
that.selectorWrapId,function(e){var target=e.target;that.hoverFlag=false;$(target).parents().each(function(i,n){if($(n).attr("id")==that.selectorWrapId)that.hoverFlag=true});if(!that.hoverFlag)that.hide()});that.selectorTxt.on("click.selector",function(){that.isShowed&&that.hide()});break;case "mouse":that.selectorOpt.on({"mouseenter":function(){clearTimeout(that.hoverTime);hoverFlag=true},"mouseleave":function(){that.hide();hoverFlag=false}});break}},_hide:function(e){var that=this,options=that.options;
that.selectorOpt.hide();that.isShowed=false},_unbindEvent:function(){var that=this,options=that.options;switch(options.targetType){case "click":$(document).off("click.selector_"+that.selectorWrapId);that.selectorTxt.off("click.selector");break;case "mouse":that.selectorOpt.off("hover");break}},_render:function(){var that=this,options=that.options,items=$(options.target).find("option"),itemsTxt="";for(var i=0,len=items.length;i<len;i++)itemsTxt+='<span class="'+options.classPre+'_opt" data-val="'+
$(items[i]).val()+'">'+$(items[i]).text()+"</span>";that.selectorOpt.html(itemsTxt);options.loaded=true;that.selectorOpt.find("span").on("click",function(){that._fill($(this))})},_fill:function(clickOpt){var that=this,options=that.options;that.selectorWrap.find("."+options.classPre+"_optCur").removeClass(options.classPre+"_optCur");clickOpt.addClass(options.classPre+"_optCur");that.selectorTxt.html(clickOpt.html());options.target.val(clickOpt.data("val"));if(!options.multiple)that.hide();switch(typeof options.evtChoose){case "function":options.evtChoose.call(clickOpt);
break;case "string":eval(options.evtChoose);break}return false}});VIPSHOP.bridgeTojQuery("Selector",VIPSHOP.Selector)})(jQuery);
(function($){VIPSHOP.declare("Template",null,{defaults:{templateElement:null,callback:null,replace:false},template:null,clTemp:"",_init:function(option){var that=this,options,target;options=that.options=$.extend({},this.defaults,option);if($.type(options.templateElement)==="object")if($(options.templateElement).length)that.template=$(options.templateElement).html();else{VIPSHOP.log("\u7f3a\u5c11\u76ee\u6807template",options);that.template="";return false}else that.template=options.templateElement;
return this},_CutTemplate:function(block,tag){var start=block.indexOf("{#"+tag+"}")+3+tag.length;var end=block.indexOf("{#/"+tag+"}",start);if(end!=-1){var tt=block.slice(start,end);block=block.substr(0,start-3-tag.length)+"{#"+tag+"}"+block.substr(end+4+tag.length)}else var tt="";return{"block":block,"section":tt}},_Table:function(block,tag,lists){var that=this,blocks=[],block=that._CutTemplate.call(this,block,tag);for(var i=0,len=lists.length;i<len;i++)blocks.push(that._Replace(block["section"],
lists[i]));return block["block"].replace("{#"+tag+"}",blocks.join(""))},_Form:function(block,tag,form){var vv=this._CutTemplate.call(this.options.node,block,tag);return vv["block"].replace("{#"+tag+"}",this._Replace(vv["section"],form))},_Replace:function(block,json){var that=this,options=that.options,element;for(element in json)if(typeof json[element]=="object")if($.isArray(json[element]))block=that._Table.call(this,block,element,json[element]);else block=that._Form.call(this,block,element,json[element]);
else{var reg=RegExp("{\\$"+element+"}","g");block=block.replace(reg,json[element])}return block},process:function(json){var that=this,options=that.options,node=$(options.node),clTemp=that.template;clTemp=that._Replace(clTemp,json);if(options.callback!=null)clTemp=options.callback(clTemp,json);if(options.replace===true)node.html(clTemp);else if(options.replace===false)node.append(clTemp);else return clTemp}});VIPSHOP.bridgeTojQuery("template,Template",VIPSHOP.Template)})(jQuery);
(function($){VIPSHOP.declare("Validation",null,{defaults:{errStyle:"",susStyle:"",msgType:"after"},rules:{required:/.+/,email:/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/,url:/^((http)|(https)|(ftp)):\/\/[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])*$/,phone:/^((\(\d{2,3}\))|(\d{3}\-))?(\(0\d{2,3}\)|0\d{2,3}-)?[1-9]\d{6,7}(\-\d{1,4})?$/,mobile:/^1\d{10}$/,chinese:/^[\u4e00-\u9fa5]+$/,english:/^[A-Za-z]+$/,currency:/^\d+(\.\d+)?$/,birthday:/^((19)|(20))(\d{2})\-((0[1-9])|1[0-2])\-((0[1-9])|([1-2][0-9])|(3[0-1]))$/,
birthday8:/^((19)|(20))(\d{2})((0[1-9])|1[0-2])((0[1-9])|([1-2][0-9])|(3[0-1]))$/,qq:/^[1-9]\d{4,13}$/,number:/^\d+$/},fields:[],_init:function(option){var that=this,options,target;options=that.options=$.extend({},this.defaults,option);if(!options.target&&!options.node){VIPSHOP.log("\u7f3a\u5c11\u76ee\u6807form");return false}else target=options.node=options.target?$(options.target):options.node;target=target[0];var elemCount=target.elements.length;that.fields=[];for(var i=0;i<elemCount;i++)that.addField($(target.elements[i]));
return that},addField:function(elem){var that=this,options=that.options,fields=that.fields;if(typeof elem=="string")elem=$(elem);if(arguments.length==1)eval("var op = "+elem.data("valid"));else var op=arguments[1];if(typeof op!="undefined"){fields.push({target:elem,option:op});elem.data({index:fields.length-1}).on("blur",function(){if($(this).val()!="")$("label[for="+$(this).attr("id")+"]").hide();else $("label[for="+$(this).attr("id")+"]").show().animate({opacity:0.5},200);that.valid($(this).data("index"))}).on("focus",
function(){if($(this).val()=="")$("label[for="+$(this).attr("id")+"]").show().animate({opacity:0.25},200);else $("label[for="+$(this).attr("id")+"]").hide()}).on("keypress change",function(){$("label[for="+$(this).attr("id")+"]").hide()})}return that},valid:function(i){var that=this,options=that.options,field=that.fields[i],isErr=false,errMsg="";for(x in field.option){var val=field.target.val();switch(x){case "func":isErr=!field.option[x][0].apply(field.target,[val]);if(isErr)errMsg=field.option[x][1];
break;case "regex":if(!field.option[x][0].test(val)){isErr=true;errMsg=field.option[x][1]}break;case "equalTo":if(val!=$(field.option[x][0]).val()){isErr=true;errMsg=field.option[x][1]}break;case "length":if(val.length<field.option[x][0]||val.length>field.option[x][1]){isErr=true;errMsg=field.option[x][2]}break;case "maxLength":if(val.length>field.option[x][0]){isErr=true;errMsg=field.option[x][1]}break;case "minLength":if(val.length<field.option[x][0]){isErr=true;errMsg=field.option[x][1]}break;
case "rang":if(val<field.option[x][0]||val>field.option[x][1]){isErr=true;errMsg=field.option[x][2]}break;case "group":var group=$("input[name='"+field.target.attr("name")+"']:checked");if(group.length<field.option[x][0]||group.length>field.option[x][1]){isErr=true;errMsg=field.option[x][2]}break;case "required":if(val==""||val=="0"){isErr=true;errMsg=field.option[x]}break;case "email":case "url":case "phone":case "mobile":case "english":case "chinese":case "currency":case "birthday":case "birthday8":case "number":if(val!=
""&&!this.rules[x].test(val)){isErr=true;errMsg=field.option[x]}break}}if(!isErr&&field.option["cb"])isErr=field.option["cb"].call(that,field.target,field.option);if(isErr)switch(options.msgType){case "alert":alert(errMsg);break;case "all":case "inner":field.target.addClass(options.errStyle).removeClass(options.susStyle);if(options.msgType=="inner")break;case "after":var id=field.target.attr("id")?field.target.attr("id"):field.target.attr("name");if($("#"+id+"_tip").length==0)field.target.after('<span id="'+
id+'_tip"></span>');$("#"+id+"_tip").addClass(options.errStyle).removeClass(options.susStyle).html(errMsg);break}else switch(options.msgType){case "all":case "inner":field.target.removeClass(options.errStyle).addClass(options.susStyle);if(options.msgType=="inner")break;case "after":var id=field.target.attr("id")?field.target.attr("id"):field.target.attr("name");if($("#"+id+"_tip").length==0)field.target.after('<span id="'+id+'_tip"></span>');$("#"+id+"_tip").removeClass(options.errStyle).addClass(options.susStyle).html("");
break}return isErr},run:function(){var fields=this.fields;var fieldCount=fields.length;var err=false;for(var i=0;i<fieldCount;i++)if(this.valid(i)||err)err=true;return err},reset:function(){var that=this,options=that.options,fields=that.fields,fieldCount=fields.length;for(var i=0;i<fieldCount;i++){var field=fields[i];switch(options.msgType){case "all":case "inner":field.target.removeClass(options.errStyle+" "+options.susStyle);if(options.msgType=="inner")break;case "after":var id=field.target.attr("id")?
field.target.attr("id"):field.target.attr("name");if($("#"+id+"_tip").length!=0)$("#"+id+"_tip").removeClass(options.errStyle+" "+options.susStyle).html("");break}}}});VIPSHOP.bridgeTojQuery("validation,Validation",VIPSHOP.Validation)})(jQuery);
(function($){VIPSHOP.declare("ScrollSpy",null,{defaults:{trigger:"",panel:"",diffHeight:0,triggerType:"click",activeCls:"cur",isAlwaysCall:true,reverse:true,speed:600,noSpyEvent:$.noop,spyEvent:$.noop,clickEvent:$.noop,_curObject:null},_init:function(option){var that=this,options,triggerDom,panelDom;options=that.options=$.extend({},this.defaults,option);if(options.target)options.node=$(options.target);that._spyArray=that.triggerDomArray=that.panelDomArray=null;that.timeStamp=+new Date;$(window).resize(function(){that._expands()});
that._expands();that._bindScroll();return that},_expands:function(trigger,panel){var tempObj,that=this,options=that.options,trigger=trigger||options.trigger,panel=panel||options.panel,triggerDomArray=that.triggerDomArray=$(trigger),panelDomArray=that.panelDomArray=$(panel),spyArray=that._spyArray;if(arguments.length==0)spyArray=[];for(var i=0,len=triggerDomArray.length;i<len;i++){tempObj={};tempObj.triggerDom=triggerDomArray.eq(i);tempObj.panelDom=panelDomArray.eq(i);if(tempObj.panelDom.offset().top>
5E4)return;tempObj.selfStartDiffHeight=tempObj.panelDom.data("startDiffHeight")||0;tempObj.selfEndDiffHeight=tempObj.panelDom.data("endDiffHeight")||0;if(options.addUp)if(i==0)tempObj.panelDom.length>0&&(tempObj.startPoint=tempObj.panelDom.offset().top);else tempObj.startPoint=spyArray[i-1].endPoint;else tempObj.panelDom.length>0&&(tempObj.startPoint=tempObj.panelDom.offset().top);tempObj.endPoint=tempObj.startPoint+(tempObj.panelDom.data("preHeight")||tempObj.panelDom.height());spyArray.push(tempObj);
that._bindClickScroll(tempObj)}that._spyArray=spyArray;return this},push:function(trigger,panel){var that=this,options=that.options;that._expands(trigger,panel);return this},refresh:function(){this._expands();return this},setDiffHeight:function(value){this.options.diffHeight=value;return this},_runFunction:function(spyObject){var that=this,options=that.options,activeCls=options.activeCls;that.triggerDomArray.removeClass(activeCls);spyObject.triggerDom.addClass(activeCls);if(options.spyEvent)options.spyEvent.call(spyObject)},
_scrollEvent:function(){var i,len,spyObject,_scrollTop,that=this,options=that.options,node=options.node,_spyArray=that._spyArray,scrollTop=node.scrollTop(),isInFlag=false;_scrollTop=scrollTop+options.diffHeight;if(!_spyArray)return;for(i=0,len=_spyArray.length;i<len;i++){spyObject=_spyArray[i];if(_scrollTop>=spyObject.startPoint-spyObject.selfStartDiffHeight&&_scrollTop<spyObject.endPoint+spyObject.selfEndDiffHeight){if(options.isAlwaysCall)that._runFunction(spyObject);else if(options._curObject!=
spyObject){that._runFunction(spyObject);options._curObject=spyObject}isInFlag=true}}if(!isInFlag){if(options.noSpyEvent&&$.isFunction(options.noSpyEvent))options.noSpyEvent();curObject=null}return this},_bindScroll:function(){var that=this,options=that.options,node=options.node,t,t_cur,t_start=+new Date;node.on("scroll.spy_"+that.timeStamp,function(){t_cur=+new Date;clearTimeout(t);if(t_cur-t_start>120){that._scrollEvent();t_start=t_cur}else t=setTimeout(function(){that._scrollEvent()},100)});that._scrollEvent();
return this},_bindClickScroll:function(spyObject){var that=this,options=that.options,triggerDomArray=that.triggerDomArray,triggerType=this.triggerType=options.triggerType+".spy_"+that.timeStamp,speed=options.speed,scrollToPoint,func,i,len;if(!options.reverse)return this;spyObject.triggerDom.off(triggerType);spyObject.triggerDom.on(triggerType,function(){var clickEvent=options.clickEvent;if(!spyObject.panelDom.length>0){VIPSHOP.log("\u6ca1\u627e\u5230\u5bf9\u5e94\u7684\u5185\u5bb9\u533a");return this}$("html, body").stop(true,
true).animate({scrollTop:spyObject.startPoint-options.diffHeight-spyObject.selfStartDiffHeight},speed);if(clickEvent)clickEvent.call(spyObject)});return this},destory:function(){var that=this,options=that.options,triggerType=this.triggerType;options.node.off("scroll.spy_"+that.timeStamp).removeData("widget_scrollspy").removeData("widget_ScrollSpy");that.triggerDomArray.off(triggerType);return}});VIPSHOP.bridgeTojQuery("scrollspy,ScrollSpy",VIPSHOP.ScrollSpy)})(jQuery);
VIPSHOP.declare("lazyDom",null,{defaults:{target:window,doc:$(document),method:"fromToBottom",targetH:0,oldTop:0,recTop:0,dataIndex:0,preHeight:200,renderCb:$.noop,isLazyLoad:true,finishEvent:$.noop,preRender:0},_init:function(option){var that=this,options;options=that.options=$.extend({},that.defaults,option);options.target=$(options.target);that.getTargetH();that.process();that.bindEvent();that.scroll();that.chkBegin();return this},process:function(){var options=this.options;var allData=this.options.allData;
for(var i=0,len=allData.length;i<len;i++){var n=allData[i];n._perNums=Math.ceil(options.targetH/n.height);n._template=$(n.template).html();n.dataLen=n.data.length;n.renderCb=n.renderCb?n.renderCb:$.noop;n.node=$(n.node)}},chkBegin:function(){var that=this;var options=that.options;var winH=options.target.height();var docH=options.doc.height();if(options.method=="fromToTop")if(docH<winH*2){var sData=that.extract(1);if(sData)setTimeout(function(){that.createDom(sData);that.chkBegin()},1)}else if(options.preRender){var sData=
that.extract(options.preRender);if(sData)that.createDom(sData)}},bindEvent:function(){var that=this;var options=this.options;options.target.on("scroll.lazyDom",function(){that.scroll()});options.target.on("resize.lazyDom",function(){that.getTargetH();that.process();that.scroll()})},getTargetH:function(){var options=this.options;options.targetH=options.target.height();return options.targetH},scroll:function(){var that=this;var options=this.options;var newTop=options.target.scrollTop();var docH=options.doc.height();
if(options.method=="fromToTop")if(newTop>options.oldTop){var scrollHeight=newTop-options.recTop;if(scrollHeight>options.targetH){var len=Math.floor(scrollHeight/options.targetH);if(docH-newTop<options.targetH)len=len+1;var sliceData=that.extract(len);if(sliceData)that.createDom(sliceData);options.recTop=newTop}options.oldTop=newTop}if(options.method=="fromToBottom")if(docH-newTop-options.targetH<=options.preHeight){var sliceData=that.extract(1);if(sliceData)that.createDom(sliceData)}},extract:function(screenNums){var that=
this;var options=that.options;var curData=options.allData[options.dataIndex];if(curData){var startCur=curData._startCur?curData._startCur:0;var endCur=startCur+curData._perNums*curData.numsPerRow*screenNums;var sliceData=curData.data.slice(startCur,endCur);var retData={node:curData.node,height:curData.height,numsPerRow:curData.numsPerRow,template:curData._template,renderCb:curData.renderCb,sliceData:sliceData,perNums:curData._perNums};curData._startCur=endCur;if(curData._startCur>=curData.data.length){options.dataIndex++;
that.scroll()}return retData}else{options.finishEvent();options.target.off("scroll.lazyDom");options.target.off("resize.lazyDom");return null}},lazyImg:false,createDom:function(createArr){var that=this;var options=this.options;var obj=createArr;var node=obj.node;var htmlArr=[];var tempInstance=$.Template({templateElement:obj.template,replace:null});for(var j=0,jLen=obj.sliceData.length;j<jLen;j++){var html=tempInstance.process(obj.sliceData[j]);htmlArr.push(html)}var fragment=$(htmlArr.join(""));
node.append(fragment);options.renderCb(node,fragment);obj.renderCb(node,fragment);if(options.isLazyLoad&&typeof $.fn.lazyload=="function")fragment.find("img.lazy").lazyload({threshold:200,failure_limit:10});createArr=null}});VIPSHOP.bridgeTojQuery("lazyDom",VIPSHOP.lazyDom);_Globals={"VipDFT":parseInt(jQuery.Cookie.get("VipDFT"))};
function fn_countDown(timestamp){var nowTime=Math.round((new Date).getTime()/1E3);var recoup=_Globals["VipDFT"]?_Globals["VipDFT"]:0;if(arguments.length>1)var lastTime=nowTime-recoup-arguments[1];else var lastTime=timestamp-nowTime-recoup;var rt={};if(lastTime>0){rt.day=Math.floor(lastTime/86400);if(!fn_countDown.hasRegulate&&rt.day>20){fn_countDown.hasRegulate=true;jQuery.ajax({url:"http://www.vip.com/index-ajax.php",data:{act:"getServerTime"},dataType:"jsonp",success:function(data){_Globals["VipDFT"]=
data.time-nowTime;jQuery.Cookie.set("VipDFT",_Globals["VipDFT"])}});return{day:"-",hour:"-",min:"-",sec:"-"}}var day_timestamp=86400*rt.day;var v="00"+Math.floor((lastTime-day_timestamp)/3600);rt.hour=v.substring(v.length-2);var hour_timestamp=3600*rt.hour;var v="00"+Math.floor((lastTime-day_timestamp-hour_timestamp)/60);rt.min=v.substring(v.length-2);var v="00"+(lastTime-day_timestamp-hour_timestamp-60*rt.min);rt.sec=v.substring(v.length-2)}else{rt.day=0;rt.hour=0;rt.min=0;rt.sec=0}return rt}
function fn_CountDown(timestamp){return fn_countDown(timestamp)}function fn_cutString(str,len){if(!str)return"";var strlen=0;var s="";for(var i=0,j=str.length;i<j;i++){if(str.charCodeAt(i)>128)strlen+=2;else strlen++;s+=str.charAt(i);if(strlen>=len)return s}return s}function SetString(str,len){return fn_cutString(str,len)}
function fn_onlineService(){var openner=null;var chatUrl="http://800.vip.com/live800/chatClient/chatbox.jsp?companyID=8900&configID=13&codeType=custom";chatUrl+="&enterurl="+encodeURIComponent(document.referrer||document.URL);chatUrl+="&t="+(new Date).getTime();try{openner=window.open(chatUrl,"chatbox143639","toolbar=0,scrollbars=0,location=0,menubar=0,resizable=1,width=900,height=720");return openner}catch(e){}}function olService(){fn_onlineService()}
function fn_share(type,info,addVmark){var pic=encodeURIComponent(info.pic),content=encodeURIComponent(info.desc),title=encodeURIComponent(info.title),url=encodeURIComponent(info.url),openner=null,openSet="width=680, height=580, toolbar=no, menubar=no, scrollbars=no, location=yes, resizable=no, status=no";if(typeof addVmark=="undefined")addVmark=true;switch(type){case "tsina":openner=window.open("http://v.t.sina.com.cn/share/share.php?title="+content+"&url="+url+"&appkey=1493335026&pic="+pic,"",openSet);
break;case "qzone":openner=window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url="+url+"&summary="+content+"&title="+title,"",openSet);break;case "tqq":openner=window.open("http://v.t.qq.com/share/share.php?title="+content+"&url="+url,"",openSet);break;case "douban":openner=window.open("http://www.douban.com/recommend/?url="+url+"&title="+content,"",openSet);break;case "kaixin001":openner=window.open("http://www.kaixin001.com/repaste/share.php?rtitle="+title+"&rurl="+url+"&rcontent="+
content,"",openSet);break;case "renren":openner=window.open("http://share.renren.com/share/buttonshare.do?link="+url,"",openSet);break;case "sohu":openner=window.open("http://t.sohu.com/third/post.jsp?&url="+url+"&title="+title+"&content=utf-8&pic=","",openSet);break;case "t163":content=title+("  "+info.url);openner=window.open("http://t.163.com/article/user/checkLogin.do?link="+url+"&source="+title+"&info="+content,"",openSet);break;default:break}if(addVmark)$.ajax({"url":"http://myopen.vip.com/my/add_vmark",
data:{type:"shareGoods"},jsonp:"callback",dataType:"jsonp",jsonpCallback:"add_vmark",success:function(res){}});return openner}function share_sns(type,info){fn_share(type,info)}
function fn_copy2Clipboard(txt){if(window.clipboardData){window.clipboardData.clearData();window.clipboardData.setData("Text",txt)}else if(navigator.userAgent.indexOf("Opera")!=-1)window.location=txt;else if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect")}catch(e){alert("\u60a8\u7684\u6d4f\u89c8\u5668\u5b89\u5168\u8bbe\u7f6e\u9650\u5236\u4e86\u60a8\u8fdb\u884c\u526a\u8d34\u677f\u64cd\u4f5c");return false}var clip=Components.classes["@mozilla.org/widget/clipboard;1"].createInstance(Components.interfaces.nsIClipboard);
if(!clip)return;var trans=Components.classes["@mozilla.org/widget/transferable;1"].createInstance(Components.interfaces.nsITransferable);if(!trans)return;trans.addDataFlavor("text/unicode");var str=new Object;var len=new Object;var str=Components.classes["@mozilla.org/supports-string;1"].createInstance(Components.interfaces.nsISupportsString);var copytext=txt;str.data=copytext;trans.setTransferData("text/unicode",str,copytext.length*2);var clipid=Components.interfaces.nsIClipboard;if(!clip)return false;
clip.setData(trans,null,clipid.kGlobalClipboard)}}function copy2Clipboard(txt){fn_copy2Clipboard(txt)}var _now=Date.now||function(){return(new Date).getTime()};
function throttle(func,wait,options){var context,args,result;var timeout=null;var previous=0;if(!options)options={};var later=function(){previous=options.leading===false?0:_now();timeout=null;result=func.apply(context,args);if(!timeout)context=args=null};return function(){var now=_now();if(!previous&&options.leading===false)previous=now;var remaining=wait-(now-previous);context=this;args=arguments;if(remaining<=0||remaining>wait){if(timeout){clearTimeout(timeout);timeout=null}previous=now;result=
func.apply(context,args);if(!timeout)context=args=null}else if(!timeout&&options.trailing!==false)timeout=setTimeout(later,remaining);return result}}
function debounce(func,wait,immediate){var timeout,args,context,timestamp,result;var later=function(){var last=_now()-timestamp;if(last<wait&&last>=0)timeout=setTimeout(later,wait-last);else{timeout=null;if(!immediate){result=func.apply(context,args);if(!timeout)context=args=null}}};return function(){context=this;args=arguments;timestamp=_now();var callNow=immediate&&!timeout;if(!timeout)timeout=setTimeout(later,wait);if(callNow){result=func.apply(context,args);context=args=null}return result}}
var UINFO={rule:{newUser:["","a","b"],oldUser:["c"]},parseCookie:function(){var uinfo=$.Cookie.get("VipUINFO");if(uinfo==="")return"";var pairs=uinfo.split("|");var result={};var i=0;var len=pairs.length;if(len>2)for(;i<len;i++){var pair=pairs[i].split(":");if(!!pair[0])result[pair[0]]=decodeURIComponent(pair[1]||"")}else result={luc:pairs[0]||"",suc:pairs[1]||""};return result},isNewUser:function(){return this.is("newUser")},isOldUser:function(){return this.is("oldUser")},is:function(ruleType,typeName){var c=
this.parseCookie();var rtn=false;typeName=typeName||"luc";var i=0;var rule=this.rule[ruleType];var len=rule.length;for(;i<len;i++)if(rule[i]===c[typeName]){rtn=true;break}return rtn}};function fn_upgrade(){delete jQuery.Loader;delete jQuery.Dialog;delete jQuery.Menu;delete jQuery.Validation;delete jQuery.fn.Switchable;delete jQuery.fn.Template;delete jQuery.fn.Selector;delete VIPSHOP}$(function(){$.Listeners.pub("ready.first").success()});
$.Listeners.sub("ready.first").onsuccess(function(){setTimeout(function(){$.Listeners.pub("ready.second").success()},2E3)});$(window).on("load.Listeners",function(){$.Listeners.sub("ready.second").onsuccess(function(){$.Listeners.pub("ready.third").success();$.Listeners.pub("winLoaded").success()})});$.Listeners.sub("ready.third").onsuccess(function(){setTimeout(function(){$.Listeners.pub("ready.four").success()},800)});$.Listeners.sub("ready.four").onsuccess(function(){$(window).one("scroll",function(){$.Listeners.pub("ready.five").success()})});
$.Listeners.sub("ready.first").onsuccess(function(){if(VIPSHOP.isIE6)$("body").on({mouseenter:function(){$(this).addClass($(this).data("hover"))},mouseleave:function(){$(this).removeClass($(this).data("hover"))}},"[data-hover]");if(VIPSHOP.isMobile){$(".device-pc").removeClass("device-pc");$("body").on("touchstart",function(e){var jqTarget=$(e.target);var isInner=false;if(typeof jqTarget.data("touch")=="undefined"){isInner=true;jqTarget=jqTarget.closest("[data-touch]")}$("[data-touch]").not(jqTarget).removeClass(function(){var className=
$(this).data("touch")||"z-touch";$(this).removeClass(className)});if(jqTarget.length!=0){var className=jqTarget.data("touch")||"z-touch";if(!jqTarget.hasClass(className))jqTarget.addClass(className);else if(!isInner)jqTarget.removeClass(className)}})}_lazyLoad()});$.Listeners.sub("ready.second").onsuccess(function(){_lazyLoad()});$.Listeners.sub("ready.third").onsuccess(function(){_lazyLoad()});
function _lazyLoad(){if($("img.lazy").length)$.Loader.advScript({name:"lazyload",url:VIPSHOP.staticJs+"/plugins/lazyload.js?"+VIPSHOP.jsVer},{name:"lazyloadAfter",def:function(){$("img.lazy").lazyload({threshold:200})},requires:["lazyload"]})}(function(){var count=1;setInterval(function(){$.Listeners.pub("interval","interval.1000").success();if(count%2===0)$.Listeners.pub("interval.2000").success();count++},1E3)})();
if(!("placeholder"in document.createElement("input"))){VIPSHOP.Placeholder={init:function(){this.addEvent();this.addStyle()},destroy:function(){this.removeEvent();this.removeStyle()},selecter:"[placeholder]",tipsSelecter:".J_placeholder",eventId:".placeholder",styleId:"vipStyle_"+(new Date).getTime(),addStyle:function(){var div=document.createElement("div");div.innerHTML="+<style id='"+this.styleId+"'>"+this.tipsSelecter+"{display:block;}</style>";$("head:first").append(div.childNodes[1]);div=null},
removeStyle:function(){var $style=$("#"+this.styleId);if(!$style[0])return this;try{$style[0].styleSheet.cssText=""}catch(e){}$style.remove()},getTips:function($target){return $target.parent().find(this.tipsSelecter)},keyup:function($target){var val=$.trim($target.val()),$tips=this.getTips($target);if(!$tips[0])return;if(!val.length)$tips.show();else $tips.hide()},keypress:function($target){var val=$.trim($target.val()),$tips=this.getTips($target);if(!$tips[0])return;$tips.hide()},addEvent:function(){var self=
this,selecter=self.selecter,eventId=self.eventId,tipsSelecter=self.tipsSelecter,$body=$("body");$body.delegate(selecter,"keyup"+eventId,function(e){self.keyup($(e.target))});$body.delegate(selecter,"keypress"+eventId,function(e){self.keypress($(e.target))});$body.delegate(tipsSelecter,"click"+eventId,function(e){var $target=$(e.target),$input=$target.parent().find(self.selecter);$input[0]&&$input.focus()})},removeEvent:function(){$("body").undelegate(this.eventId);$body.undelegate(this.selecter,"placeholder")}};
$(function(){VIPSHOP.Placeholder.init()})}
$.Mod=function(){var Collection={};var errorMsg="depMods only accept string type value!";return{"get":function(modName){return modName?Collection[modName]:Collection},"add":function(modName,ready,depMods){depMods=depMods||"";ready=ready||1;if($.type(depMods)!="string")VIPSHOP.log(errorMsg);Collection[modName]={"level":ready,"depMods":depMods}},"init":function(){for(var modName in Collection){var curMod=Collection[modName];var Listenfunc=function(modName){return function(){eval(modName+".init()")}}(modName);
if(!curMod.depMods){var levelMaps={1:"ready.first",2:"ready.second",3:"ready.third"};var levelName=levelMaps[curMod.level];$.Listeners.sub(levelName).onsuccess(Listenfunc)}else $.Listeners.sub(curMod.depMods).onsuccess(Listenfunc)}}}}();
$.Var=function(){var Collection={};var lastMethods={"set":function(currObj,key,value){currObj[key]=value;return currObj[key]},"get":function(currObj,key){return currObj[key]},"del":function(currObj,key){delete currObj[key]},"add":function(currObj,key,value){currObj[key]=$.extend(currObj[key],value)}};var objCtrl=function(type,variable,value){var varArr=variable.split(".");var currObj=Collection;var lastEvt=lastMethods[type];for(var i=0,len=varArr.length;i<len;i++)if(i==len-1)return lastEvt(currObj,
varArr[i],value);else{if(type=="get"&&!currObj[varArr[i]])return;if($.type(currObj[varArr[i]])=="object")currObj[varArr[i]]=currObj[varArr[i]];else currObj[varArr[i]]={};currObj=currObj[varArr[i]]}};return{"set":function(variable,value){return objCtrl("set",variable,value)},"get":function(variable){return objCtrl("get",variable)},"del":function(variable){return objCtrl("del",variable)},"add":function(variable,value){objCtrl("add",variable,value)}}}();
