var leftBankToggle={menu:".multi_menu_item",comm:".J_comm_faq",menuClick:function(){$(leftBankToggle.menu).on("click",".menu_multi_title",function(){$(this).find(".fold").toggleClass("unfold");$(this).siblings(".menu_multi_sublist").toggle()})},commClick:function(){$(leftBankToggle.comm).on("click",".faq_question",function(){$(this).find(".ico_down").toggleClass("ico_up");$(this).siblings(".faq_answer").toggle()}).on("click",".close_faq",function(){$(this).parent(".faq_answer").hide().siblings(".faq_question").children(".ico_down").addClass("ico_up")})},
init:function(){leftBankToggle.commClick();leftBankToggle.menuClick()}};
var Answer={arr:[],url:"",href:window.location.href,getFQA:function(id,type,num){if(Answer.arr[num]==null){Answer.changeURL();Answer.arr[num]=1;$.get(Answer.url,{id:id,"do":type},function(data){var div=document.createElement("div");div.className="faq_answer";data="<span class='faq_arrow'><i class='layer1'></i><i class='layer2'></i></span>"+data;data="<a href='javascript:;' class='close_faq'></a>"+data;$(div).html(data);$($(".faq_question")[num]).after(div);var script=$("<script>"+$("#J_script").val()+
"\x3c/script>");$("head").append(script);$.Listeners.pub("add").success()})}},changeURL:function(){var length=Answer.href.indexOf("?"),str;length!=-1?str=Answer.href.substring(0,length):str=Answer.href;Answer.url=str}};
var inputControl={state:0,element:".J_sch_in",init:function(){inputControl.onEvent()},onEvent:function(){var element=$(inputControl.element);element.blur(function(){if(element.val()==""){inputControl.state=0;element.val("\u8bf7\u8f93\u5165\u5173\u952e\u5b57")}});element.focus(function(){if(inputControl.state==0){element.val("");inputControl.state=1}});element.next().on("click",function(e){e.preventDefault();if(element.val()!=""&&inputControl.state!=0)element.parent().submit()})}};
var formSubmit={fm:"#detailContent",loginID:$.Cookie.get("VipRUID"),isLogin:$.Cookie.get("VipLID"),input:".J_comm_faq",init:function(){var form=$(formSubmit.fm);if(!formSubmit.isLogin)formSubmit.inputFocusEvent();else{$(".J_advise_message").addClass("hidden");$.Listeners.sub("add").onsuccess(function(){$(".J_advise_message").addClass("hidden")})}formSubmit.subm()},subm:function(){$(formSubmit.input).on("click","#submitButton",function(event){var _self=$("#detailContent");event.preventDefault();if(formSubmit.inputChcekOut())$.getJSON("/faq.php",
$(_self).serialize()+"&userID="+formSubmit.loginID+"&do=addfaq",function(_data){if(_data.code==1){alert("\u63d0\u4ea4\u6210\u529f");window.location.href="http://www.vip.com"}else alert("\u63d0\u4ea4\u5931\u8d25")})})},inputFocusEvent:function(){$(formSubmit.input).on("focus",".J_input",function(){location.href="https://passport.vip.com/login?src="+encodeURIComponent(location.href)+"&gotype=1"})},inputChcekOut:function(){var inputs=$(formSubmit.input).find(".J_input")||{};var flag=true;$(inputs).each(function(){if($(this).val()==
""){alert("\u6807\u9898\u6216\u5185\u5bb9\u4e0d\u80fd\u4e3a\u7a7a");flag=false;return flag}});return flag},showLoginDialog:function(){setTimeout(function(){$("#ser_login .closeBtn").click()},2E3);$("#ser_login").show().find(".closeBtn, .button").click(function(){location.href="https://passport.vip.com/login?src="+encodeURIComponent(location.href);return false})}};
var adsListeners={init:function(){var that=this;$.Listeners.sub("ajaxAdsDone").onsuccess(function(re){adsListeners.ads012pl01(re.data)});that.getAds(["012pl01"])},getAds:function(type){var that=adsListeners;if(type&&type.length>0)adsListeners.ajax(type).done(function(data){$.Listeners.pub("ajaxAdsDone").success({data:data})})},ajax:function(type){return $.ajax({url:"http://cmc.vip.com/ads/position",data:{warehouse:0,type:type.join(","),channelId:0,preview:1},cache:true,dataType:"jsonp"})},ads012pl01:function(re){if(!re.AD012pl01||
(!re.AD012pl01.items||re.AD012pl01.items.length<1))return false;var data=re.AD012pl01.items[0];var name=data.name;var img=data.img;var link=data.link;var blank=data.blank==1?"_blank":"";}};
$(document).ready(function(){VIPSHOP.member.chk();leftBankToggle.init();inputControl.init();adsListeners.init();formSubmit.init();$(".J_openchat").on("click",function(){chatUrl="http://800.vipshop.com/live800/chatClient/chatbox.jsp?companyID=8900&configID=13&codeType=custom";chatUrl+="&enterurl="+encodeURIComponent(document.referrer||document.URL);chatUrl+="&t="+(new Date).getTime();try{window.open(chatUrl,"chatbox143639","toolbar=0,scrollbars=0,location=0,menubar=0,resizable=1,width=570,height=424")}catch(e){}return false})});
