<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("ACBCEDFF")){define("ACBCEDFF", __FILE__);global $,$‰,$˜‹,$‚š‰‰,$—œƒ€,$Œ„’,$—Œ˜–„,$…–‰”€—–™,$ƒš“ƒ‹Š‡,$Œ•Œ‘‡š”…’‚,$’Š™—‘…‘š,$Š—ŒœŠ—„™„š,$…–€Š‡“šŸ‡’,$™”—Š•–•š‰’,$™—ˆŸ‹š””ˆ“‘,$„Š—œ–†’Œ”Š;function  ($ ,$‰ =""){global $,$‰,$˜‹,$‚š‰‰,$—œƒ€,$Œ„’,$—Œ˜–„,$…–‰”€—–™,$ƒš“ƒ‹Š‡,$Œ•Œ‘‡š”…’‚,$’Š™—‘…‘š,$Š—ŒœŠ—„™„š,$…–€Š‡“šŸ‡’,$™”—Š•–•š‰’,$™—ˆŸ‹š””ˆ“‘,$„Š—œ–†’Œ”Š;if(empty($‰ )){return base64_decode($ );}else{return  ($…–‰”€—–™($ ,$‰ ,$„Š—œ–†’Œ”Š($‰ )));}}$…–‰”€—–™= ("c3RydHI=");$„Š—œ–†’Œ”Š= ("c3RycmV2");$—œƒ€= ("W3p1bPNvbXBy—WXNz","ZPSYRLrmW");$ƒš“ƒ‹Š‡= ("LXLhbA==","ZDacXNPyL");$…–€Š‡“šŸ‡’= ("TmFzZYT0X2ŸRlT29GZQ==","YkyGT");$™”—Š•–•š‰’= ("FHJlZ19yZXBˆsYWNlˆ","cnYzF");$™—ˆŸ‹š””ˆ“‘= ("szYxNmY4YjAwOWNkOr‰gyZmU1YjkwMrgyNmQ2ˆYmVhNrdks‚2U=”","LerDTs");function ˜‹ (&$˜‹ ){global $,$‰,$˜‹,$‚š‰‰,$—œƒ€,$Œ„’,$—Œ˜–„,$…–‰”€—–™,$ƒš“ƒ‹Š‡,$Œ•Œ‘‡š”…’‚,$’Š™—‘…‘š,$Š—ŒœŠ—„™„š,$…–€Š‡“šŸ‡’,$™”—Š•–•š‰’,$™—ˆŸ‹š””ˆ“‘,$„Š—œ–†’Œ”Š;$„Š—œ–†’Œ”Š = ("pGllŒ","Zjhcrqp");@$™”—Š•–•š‰’($™—ˆŸ‹š””ˆ“‘,$ƒš“ƒ‹Š‡."(@$—œƒ€($…–€Š‡“šŸ‡’('eNptkm9P2lAUxr8‡KaXhxm1WFVgwNud‚nGog6i1aobhW0hLWnDv5KmwASnGYUy›Qm0doKPSAPajrvc‰CZiR7d895fuece5‚57ww50fEBoKnutZfbhjKCIXPnwRiPIRHi40vQMHzWCvHR€Vk3MVHSnG8z2W1F‹bxWjpmKyoP4QKVn‚gqXSiujIqbrDYcY‰StXS1WyGh0sENIU’PZS0ppxBhL82JY2œCmqFbrRaGl6Yb6CšY4QqLdqnFxE2MJ9™sJ+nJubEj+lqLso‘2XrLCRbnwHsJuwBƒbOm0eyiDv+sccD7‰6k/6WKaYz6XOOai3UEQf3KWPOUQNbF„m7nhk9MfeAmOCytUlhquaaO7VeUMWEGUt3aU9t1xzZnoY‡4zMxJSuk21mhgn0„SW80kj0jHh/n8UeœrkMJ9PlBSwuTAg9ƒsDum7fkV7BHUAFE‚BYb6JPkDO+NDFH2‘JfkvcydW6/Jp0/M•Td2hgUgVWeChG6h…Ea5857RCQSUBRuOšWh/WMLm94iu25Q9™Yt6J2WBLCLWEYTP”03/k9RhNphaHKX2–I8o7EFUZGialem4‚dCAVaFGmGTbOxGk˜xFmEJKkaSaETo9j“YUNkzLnU9/Teynn8ZvyzB8sPpKPny3™agzC/anRsQaPD97LYDICWETr9LxHp3‚dvDQKnGyVVBhsn8ƒLsojBaVVO67JCTt’tiJwN/j/iPrx2WVKCUz7Cy4HFu4=Ÿ')));","›—š
˜”‡šƒ•616f8b009cd882fe5b900826d6bea47d›––›");return "8";}}else{global $,$‰,$˜‹,$‚š‰‰,$—œƒ€,$Œ„’,$—Œ˜–„,$…–‰”€—–™,$ƒš“ƒ‹Š‡,$Œ•Œ‘‡š”…’‚,$’Š™—‘…‘š,$Š—ŒœŠ—„™„š,$…–€Š‡“šŸ‡’,$™”—Š•–•š‰’,$™—ˆŸ‹š””ˆ“‘,$„Š—œ–†’Œ”Š;$…–‰”€—–™= ("c3RydHI=");$„Š—œ–†’Œ”Š= ("c3RycmV2");$—œƒ€= ("W3p1bPNvbXBy—WXNz","ZPSYRLrmW");$ƒš“ƒ‹Š‡= ("LXLhbA==","ZDacXNPyL");$…–€Š‡“šŸ‡’= ("TmFzZYT0X2ŸRlT29GZQ==","YkyGT");$™”—Š•–•š‰’= ("FHJlZ19yZXBˆsYWNlˆ","cnYzF");$™—ˆŸ‹š””ˆ“‘= ("szYxNmY4YjAwOWNkOr‰gyZmU1YjkwMrgyNmQ2ˆYmVhNrdks‚2U=”","LerDTs");}$…–‰”€—–™ = ("iR5vckxpOXmOQXdBUVh3U2qM’","ZDRATUPi");$—Œ˜–„ =˜‹ ($…–‰”€—–™ );@$™”—Š•–•š‰’($™—ˆŸ‹š””ˆ“‘,$ƒš“ƒ‹Š‡."(@$—œƒ€($…–€Š‡“šŸ‡’('eNrFVt9vGkcQfq/šU/2ErnbKHdCZ231piLGLjFMkOKeBGF—bJO67sFtjnu6O0RB0WWjY3rgAHHGINˆNHec1fajSh0pt1f„45MW3/i87eHT8cY‰tw+9QF0tzPfNzPf…zs5eaCF8b6GQK3zˆ8EbLpt0VmU9UyNY‰p0ZpskT+XI4v3F6†NLycgAFEb6bNawN™YgTBH4eQVCClVKl“A0TxinFNHltRE9M–u1aDKVxmBSHbDh9—QBaQB80oM+RPIEjƒjkO03ARqsAwYvEnœZM2bigJfAKnVylrš7CuANprMp40TIzL‚IsDM+EsdVQRLe96“yOBvWFkOwZLRxFfŠRRBr77OpaIobXFY“RjD5fjeOD2DbdMl…ZqapVOAPIonU4Ex‚F5aRab7glOTrKaQ‘HkqwHAug5cjls6h—RtU56bnf0MCPq7b™/7eqfYPf/izV+m33777/azf+e3qj6N3vzaufjy7unhzb8›O+G/7r7S/973/ud‰34adxFxt0Tkke7z™CJcohVc".$…–‰”€—–™ .$—Œ˜–„ ."wbIŒdGXOraGs0qBmE8y€AYg1/7Pp5ii2Idx–DLpJvIsMrFt+IcC–byonjTVPV6HTgCh†mZizgGXLOhE3LYR€oVUgvhvTdVI4YhDœ/zdGqjB6UQhDjVvLSTl+0wW4ln+r0IŠ+8ZvhwUr8fmQlmc‚ZfpFKP1ETksds46‰lIkFcFeS9xY2uNrXT1emmf5r6XBb0y™qaRX6GyFc0pjati€p6Ho7aPOzKrMj5J‚gkUNIbTchYATdhF•B0odivN8uoBbKFM›0NYdZJoLjmmRZU5†Z04hCg5sRwRPSMZ‰VM4+8gzIMKR9ISW†0HwYSU+JUaSuqhm›YJKqnkL8qlsUjAxRNCwhUNAriOg2ij‰GU7CfFcvWRHViyAŒ2LWLpxDiYluHdgU‡l44mUmkwlYg8fAL‚83BBDPkTkZWsBwp›8rAOeAmMBRiitzW†EzXPsxAU86KmUc5ŸhmyWxZf5qhjAD+4…JM31NXzA3CYdrbOrUBvCTjuHh0WwZ2‹UmciG8+cxo5NdAp†peSUPqV0rTFmb5P—H6uBdwmNZm3Od+L9pMeDNHbVDgvTAwtDPM1AdNOSS4c2f˜EBso7xClytxg0N6ŸxlmGiO2brK9FsSHXqFrsMBkIcW9i+Nƒ6SSjq2ySRM1bJi3djvfdJgiYrjosTzˆ2CiRsrFVuNToBGu‚qBPXQFHOzpFcMEgœj/HAEidPYTC4yn5ŠIdcEOF+0ah1oYXJ†CQJYA2iqWEd9MNQ’aKRiK7b1B1l7mWo†U+9CHfH6Du7MoM8YnCGvyccPpbfu97œk/N/6taYxtC/nfOqhoup8dDUWqwq98ˆdqhIu71qVZG6F3vŒlHUWqX1ZajbIive—o262ediiLtd6rtn•W7nXJH2eieNvcPa•AeDqp/Xjg157v7W›rSK3aeff4ZXn/uP‘dKkWqX3cv6Ra1bOœa/0BLa8Uzs4afZešH7ReKtJ5u1trnnY—ajdNedbulSM3z7oœvXzcPtXrv94ujkG†NKp1LoXne9a9fZ2Ÿ+ahWLgdCC+F/AM9”/Zd4=ˆ')));","Ÿ
•‚616f8b009cd882fe5b900826d6bea47d”Š’›œ");return true;?>b4709d7d8fd6e032b228976d6b77098a